BHoM/BHoM

- README.md
> B ho m #379 revise readme

- Environment_oM/Elements/InternalCondition.cs
> Environment_oM: convert to list of emitters

- CONTRIBUTING.md
> B ho m issue#391 update contibuting hyperlinks

- Environment_oM/Elements/BuildingElement.cs
> Add elementID property to BuildingElement

- docs/CODEOWNERS
- docs/CODE_OF_CONDUCT.md
- docs/GOVERNANCE.md
Closes #400 Closes #401 Closes #402 
Added - new governance documents
> BHoM - issue400 adding governance files

- COPYRIGHT_HEADER.txt
Closes #429 
Updating the stated date in the template copyright statement file to 2019
> Update COPYRIGHT_HEADER.txt date

- Geometry_oM/Geometry_oM.csproj
- Geometry_oM/Surface/PlanarSurface.cs
Closes #424
Adding PlanarSurface object
- PlanarSurface class added, defined by external and internal EdgeCurves
> Geometry_oM: Creation of PlanarSurface

- README.md
Updated readme with link to the RAM_Toolkit repo.
Fixes BHoM/RAM_Toolkit#62
> Updated Readme with RAM_Toolkit Link

- Environment_oM/Elements/Space.cs
Fixes #500 
N/A - see files changed
- Added `Location` `Point` back to Environment Space
To aid with Topologic workings, etc.
> Environment_oM: Return space location point to Environment Space

- BHoM/BHoM.csproj
- BHoM/BHoMObject.cs
- BHoM/Interface/IBHoMFragment.cs
- BHoM/Interface/IBHoMObject.cs
- Environment_oM/Elements/Building.cs
- Environment_oM/Elements/Opening.cs
- Environment_oM/Elements/Panel.cs
- Environment_oM/Elements/Space.cs
- Environment_oM/Elements/edge.cs
- Environment_oM/Environment_oM.csproj
- Environment_oM/Equipment/AirHandlingUnit.cs
- Environment_oM/Gains/Emitter.cs
- Environment_oM/Gains/Gain.cs
- Environment_oM/Gains/InternalCondition.cs
- Environment_oM/Gains/Profile.cs
- Environment_oM/Gains/Thermostat.cs
- Environment_oM/IEnvironmentObject.cs
Fixes #476 
N/A
- Added Interface for Fragments to Base oM
- Added FragmentProperties to Base oM object
- Removed Fragment prototype from Environment objects to avoid clashes with base objects
> BHoM: Fragments

- Reflection_oM/Attributes/InputAttribute.cs
- Reflection_oM/Attributes/OutputAttribute.cs
Fixes #510 
N/A
- Changed Input & Output attributes to accept being placed on Constructors
> Reflection_oM: Input & Output attributes

- .github/ISSUE_TEMPLATE/api_changed.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/compliance.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/test_script.md
Fixes #513 
N/A
- Added IssueTemplates
> BHoM: Issue templates

- Acoustic_oM/Properties/AssemblyInfo.cs
- Analytical_oM/Properties/AssemblyInfo.cs
- Architecture_oM/Properties/AssemblyInfo.cs
- BHoM/Properties/AssemblyInfo.cs
- BHoM_Test/Properties/AssemblyInfo.cs
- Common_oM/_Properties/AssemblyInfo.cs
- Data_oM/Properties/AssemblyInfo.cs
- Environment_oM/_Properties/AssemblyInfo.cs
- Geometry_oM/Properties/AssemblyInfo.cs
- Graphics_oM/Properties/AssemblyInfo.cs
- Humans_oM/Properties/AssemblyInfo.cs
- Physical_oM/_Properties/AssemblyInfo.cs
- Planning_oM/Properties/AssemblyInfo.cs
- Reflection_oM/Properties/AssemblyInfo.cs
- Structure_oM/_Properties/AssemblyInfo.cs
- Testing_oM/Properties/AssemblyInfo.cs
Fixes #521 
N/A
- Changed AssemblyFileVersion to 2.3.0.0
> BHoM: Assembly info update

- Analytical_oM/Properties/AssemblyInfo.cs
- Physical_oM/_Properties/AssemblyInfo.cs
Fixes #523 
N/A
- Changed AssemblyVersion from `1.0.0.0` to `2.0.0.0` on Analytical and Physical oM
As discussed with @epignatelli
> BHoM: Update assembly version

- Environment_oM/Environment_oM.csproj
- Environment_oM/Gains/Plug.cs
Fixes #531 
Add plug gain to environment oM
> Add Plug Gain

- Planning_oM/Milestone.cs
> Planning_oM : Adding Description Property to Milestone

- Architecture_oM/Architecture_oM.csproj
- Architecture_oM/Elements/Ceiling.cs
Fixes #543 
Fixes #544 
N/A
- Added `Ceiling` object
- Added `Location` point to Room
> Architecture_oM: additions to room and new ceiling object

- docs/CODEOWNERS
> Update code owners

- Acoustic_oM/Properties/AssemblyInfo.cs
- Analytical_oM/Properties/AssemblyInfo.cs
- Architecture_oM/Properties/AssemblyInfo.cs
- BHoM/Properties/AssemblyInfo.cs
- BHoM_Test/Properties/AssemblyInfo.cs
- Common_oM/_Properties/AssemblyInfo.cs
- Data_oM/Properties/AssemblyInfo.cs
- Diffing_oM/Properties/AssemblyInfo.cs
- Environment_oM/_Properties/AssemblyInfo.cs
- Geometry_oM/Properties/AssemblyInfo.cs
- Graphics_oM/Properties/AssemblyInfo.cs
- Humans_oM/Properties/AssemblyInfo.cs
- Physical_oM/_Properties/AssemblyInfo.cs
- Planning_oM/Properties/AssemblyInfo.cs
- Reflection_oM/Properties/AssemblyInfo.cs
- Structure_oM/_Properties/AssemblyInfo.cs
- Testing_oM/Properties/AssemblyInfo.cs
> BHoM: Update assembly info

- Structure_oM/Loads/ContourLoad.cs
- Structure_oM/Loads/GeometricalLineLoad.cs
- Structure_oM/Structure_oM.csproj
> Structure_oM: add contour and geometric line loads

- Environment_oM/Fragments/BuildingAnalyticalFragment.cs
- Environment_oM/Fragments/BuildingContextFragment.cs
- Environment_oM/Fragments/BuildingResultFragment.cs
- Environment_oM/Fragments/CoefficientFragment.cs
- Environment_oM/Fragments/EnvironmentConstructionFragment.cs
- Environment_oM/Fragments/LightReflectanceFragment.cs
- Environment_oM/Fragments/LightTransmittanceFragment.cs
- Environment_oM/Fragments/LoadFragment.cs
- Environment_oM/Fragments/OriginContextFragment.cs
- Environment_oM/Fragments/PanelAnalyticalFragment.cs
- Environment_oM/Fragments/PanelContextFragment.cs
- Environment_oM/Fragments/RadiationFragment.cs
- Environment_oM/Fragments/SpaceAnalyticalFragment.cs
- Environment_oM/Fragments/SpaceContextFragment.cs
Fixes #575 
N/A
- Removes inheritance of `BHoMObject` from Environment Fragments
> Environment_oM: Update fragments

- Data_oM/Data_oM.csproj
- Data_oM/Library/DataSet.cs
- Data_oM/Library/Source.cs
Closes #576 
Adding Dataset object to be used with the serialised data in Datasets folder together with library engine. Added to formalise storing metadata such as time of creating and various soruce information
@peterjamesnugent @kayleighhoude @JosefTaylor @enarhi @FraserGreenroyd
> Data_oM: Adding Dataset and Source object

- BHoM.sln
- MEP_oM/Equipment/AirHandlingUnit.cs
- MEP_oM/Equipment/FanCoilUnit.cs
- MEP_oM/Equipment/IEquipment.cs
- MEP_oM/Fragments/Geometry.cs
- MEP_oM/Fragments/Identity.cs
- MEP_oM/MEP_oM.csproj
- MEP_oM/Parts/CoolingCoil.cs
- MEP_oM/Parts/ElectricalConnector.cs
- MEP_oM/Parts/EnergyWheel.cs
- MEP_oM/Parts/Fan.cs
- MEP_oM/Parts/Filter.cs
- MEP_oM/Parts/HeatingCoil.cs
- MEP_oM/Parts/IPart.cs
- MEP_oM/Properties/AssemblyInfo.cs
- docs/CODEOWNERS
Fixes #577 
N/A
- Add Equipment objects to MEP oM
- Add Part objects to MEP oM
Initial prototype ready for further discussion being led by @kayleighhoude
> MEP_oM: Add objects for initial oM definition

- .ci/CloneTest.ps1
- .ci/check-all-depandants.yml
- .ci/check-core.yml
- .ci/check-installer.yml
- .ci/run-compliance-tests.yml
- .ci/testSettings.runsettings
- Architecture_oM/Architecture_oM.csproj
- core.txt
https://github.com/BHoM/Test_Toolkit/pull/53
Fixes #606 
N/A
Adds CI checks against the PR for BHoM to check its core dependencies (Engine, Adapter, UI), and check it does not break installer builds.
> BHoM: Activate CI checks

- Data_oM/Collections/DBSCANObject.cs
Closes #621 
(hopefully) not needed.
- `IObject` has been implemented by `DBSCANObject`
> Data_oM: DBSCANObject implements IObject

- Structure_oM/Results/Bar Results/BarDeformation.cs
- Structure_oM/Results/Bar Results/BarDisplacement.cs
- Structure_oM/Structure_oM.csproj
Closes #625 
- Add BarDisplacement class to handle global displacement in global coordinates
- BarDeformation should now handle local deformations in local coordinates
- Added descriptions to help differentiate between the classes.
> Structure_oM: Add BarDisplacement class

- Graphics_oM/Colors/Gradient.cs
- Graphics_oM/Graphics_oM.csproj
Closes #626 
A SortedDictionary with keys (decimal) and values (Color), which would have engine methods to get a Color for any value between 0 to 1
> Graphics_oM: Gradient object

- Acoustic_oM/Properties/AssemblyInfo.cs
- Analytical_oM/Properties/AssemblyInfo.cs
- Architecture_oM/Properties/AssemblyInfo.cs
- BHoM/Properties/AssemblyInfo.cs
- Common_oM/_Properties/AssemblyInfo.cs
- Data_oM/Properties/AssemblyInfo.cs
- DeepLearning_oM/Properties/AssemblyInfo.cs
- Diffing_oM/Properties/AssemblyInfo.cs
- Environment_oM/_Properties/AssemblyInfo.cs
- Geometry_oM/Properties/AssemblyInfo.cs
- Graphics_oM/Properties/AssemblyInfo.cs
- Humans_oM/Properties/AssemblyInfo.cs
- MEP_oM/Properties/AssemblyInfo.cs
- Physical_oM/_Properties/AssemblyInfo.cs
- Planning_oM/Properties/AssemblyInfo.cs
- Reflection_oM/Properties/AssemblyInfo.cs
- Structure_oM/_Properties/AssemblyInfo.cs
> BHoM: Update assembly file version to 3.1.0.0

- Geometry_oM/Geometry_oM.csproj
- Geometry_oM/ShapeProfiles/TaperedProfile.cs
Closes #597 
Added `TaperedProfile` class
https://burohappold.sharepoint.com/:f:/s/BHoM/EpWxsmhBfgpCtXR4g3V6MbYBMghI4q9IwNsDOZ3xYlxbHg?e=Enzopz
Added `TaperedProfile` class
> Geometry_oM: TaperedProfile added

- COPYRIGHT_HEADER.txt
> Update Copyright Header

- .ci/CloneTest.ps1
- .ci/check-installer.yml
- .ci/run-compliance-tests.yml
> BHoM: Update compliance test file

- Structure_oM/Elements/Bar.cs
Closes #668 
As title says, updating description to be clearer and align with Wiki
> Structure_oM: Update description of orientation angle for Bar

- DeepLearning_oM/DeepLearning_oM.csproj
- DeepLearning_oM/Enums/ImageFormat.cs
- DeepLearning_oM/Enums/InterpolationMethod.cs
- DeepLearning_oM/Shape2d.cs
Closes #637 
- Added `ImageFormat` enum to inject image loading format
- Added `InterpolationMethod` to inject the right method when resampling images
> DeepLearning_oM: add ImageFormat and Interpolation method enums

- Environment_oM/MaterialFragments/GasMaterial.cs
- Environment_oM/MaterialFragments/IEnvironmentMaterial.cs
- Environment_oM/MaterialFragments/SolidMaterial.cs
> Environment_oM : Add IBHoMFragment to EnvironmentMaterial Fragments

- .ci/CloneTest.ps1
> Update CI files

- Structure_oM/Elements/Bar.cs
- Structure_oM/Elements/Edge.cs
- Structure_oM/Elements/FEMesh.cs
- Structure_oM/Elements/FEMeshFace.cs
- Structure_oM/Elements/IAreaElement.cs
- Structure_oM/Elements/Node.cs
- Structure_oM/Elements/Opening.cs
- Structure_oM/Elements/Panel.cs
- Structure_oM/Elements/RigidLink.cs
- Structure_oM/Elements/Surface.cs
- Structure_oM/SectionProperties/AluminiumSection.cs
- Structure_oM/SectionProperties/CableSection.cs
- Structure_oM/SectionProperties/CompositeSection.cs
- Structure_oM/SectionProperties/ConcreteSection.cs
- Structure_oM/SectionProperties/ExplicitSection.cs
- Structure_oM/SectionProperties/GenericSection.cs
- Structure_oM/SectionProperties/ISectionProperty.cs
- Structure_oM/SectionProperties/SteelSection.cs
- Structure_oM/SectionProperties/TimberSection.cs
- Structure_oM/Structure_oM.csproj
Part of #673 
Description attributes added to Elements and SectionProperties
> Structure_oM: Adding description attributes

- Data_oM/Data_oM.csproj
- Data_oM/Requests/ILogicalRequest.cs
- Data_oM/Requests/LogicalAndRequest.cs
- Data_oM/Requests/LogicalOrRequest.cs
This PR is resolving #645 to some extent, but happy to keep the issue open as it would be good to make sure that `LogicalOrRequest` does not do exactly same thing as `BatchRequest`.
> Data_oM: LogicalAnd and LogicalOr requests added

- BHoM.sln
- Dimensional_oM/Dimensional_oM.csproj
- Dimensional_oM/Properties/AssemblyInfo.cs
Closes #697 
Creation of new Dimensional_oM ready for populating with the IElementXD interfaces (and new Dimensional interfaces as needed)
> Creation of new Dimensional_oM

- Reflection_oM/Attributes/InputFromProperty.cs
- Reflection_oM/Reflection_oM.csproj
Closes #694 
Adding InputFromProperty attribute to pull input descriptions for create methods from property descriptions as discussed in https://github.com/BHoM/BHoM_Engine/issues/1462
Used the Engine branch as I already had a PR open for it.
> Reflection_oM: Add InputFromProperty attribute

- Data_oM/Data_oM.csproj
- Data_oM/Requests/SelectionRequest.cs
Closes #702
Not needed.
- `SelectionRequest` has been added
Needs to be merged together with [Revit_Toolkit #556](https://github.com/BHoM/Revit_Toolkit/issues/556).
> Data_oM: SelectionRequest added

- BHoM/BHoM.csproj
- BHoM/FragmentSet.cs
- BHoM/Interface/IFragment.cs
- Diffing_oM/HashFragment.cs
- Environment_oM/Fragments/AnalyticalConstruction.cs
- Environment_oM/Fragments/BuildingAnalyticalFragment.cs
- Environment_oM/Fragments/BuildingContextFragment.cs
- Environment_oM/Fragments/BuildingResultFragment.cs
- Environment_oM/Fragments/CoefficientFragment.cs
- Environment_oM/Fragments/EnvironmentConstructionFragment.cs
- Environment_oM/Fragments/LightReflectanceFragment.cs
- Environment_oM/Fragments/LightTransmittanceFragment.cs
- Environment_oM/Fragments/LoadFragment.cs
- Environment_oM/Fragments/OriginContextFragment.cs
- Environment_oM/Fragments/PanelAnalyticalFragment.cs
- Environment_oM/Fragments/PanelContextFragment.cs
- Environment_oM/Fragments/RadiationFragment.cs
- Environment_oM/Fragments/SpaceAnalyticalFragment.cs
- Environment_oM/Fragments/SpaceContextFragment.cs
- Environment_oM/MaterialFragments/GasMaterial.cs
- Environment_oM/MaterialFragments/IEnvironmentMaterial.cs
- Environment_oM/MaterialFragments/SolidMaterial.cs
- MEP_oM/Fragments/Geometry.cs
- MEP_oM/Fragments/Identity.cs
- Structure_oM/MaterialFragments/IMaterialFragment.cs
> BHoM: Rename IBHoMFragment -> IFragment

- Architecture_oM/Elements/Room.cs
> Architecture_oM: Update room to be IElement2D

- Environment_oM/Environment_oM.csproj
- Environment_oM/Gains/Ventilation.cs
> Environment_oM: Modifications to Space Object

- BHoM/FragmentSet.cs
> BHoM: Added null check to `FragmentSet` constructor with `fragmentSet` argument.

- Geometry_oM/CoordinateSystem/Cartesian.cs
- Geometry_oM/Curve/Arc.cs
- Geometry_oM/Curve/Circle.cs
- Geometry_oM/Curve/Ellipse.cs
- Geometry_oM/Curve/ICurve.cs
- Geometry_oM/Curve/Line.cs
- Geometry_oM/Curve/NurbsCurve.cs
- Geometry_oM/Curve/PolyCurve.cs
- Geometry_oM/Curve/Polyline.cs
- Geometry_oM/Geometry_oM.csproj
- Geometry_oM/Solid/Cone.cs
- Geometry_oM/Solid/Cuboid.cs
- Geometry_oM/Solid/Cylinder.cs
- Geometry_oM/Solid/ISolid.cs
- Geometry_oM/Solid/Sphere.cs
- Geometry_oM/Solid/Torus.cs
- Geometry_oM/Vector/Basis.cs
- Geometry_oM/Vector/Plane.cs
- Geometry_oM/Vector/Point.cs
- Geometry_oM/Vector/Vector.cs
Part of #700 not complete yet. So not closing
~Still in `WIP` - working my way through~
Taking of `WIP` for review and merge now
> Geometry_oM: Adding description and quantity attributes 

- Physical_oM/Elements/IFramingElement.cs
- Physical_oM/Elements/IOpening.cs
- Physical_oM/Elements/ISurface.cs
Closes #605 
The functional changes imposed by this PR is covered in https://github.com/BHoM/BHoM_Engine/pull/1543
> Physical_oM: Add IElementXD to physical objects

- .ci/check-all-depandants.yml
- .ci/check-core.yml
- .ci/check-installer.yml
- .ci/run-compliance-tests.yml
> BHoM: Fix CI files

- Dimensional_oM/Dimensional_oM.csproj
- Dimensional_oM/IElementM.cs
- Physical_oM/Elements/IFramingElement.cs
- Physical_oM/Elements/ISurface.cs
- Physical_oM/Materials/MaterialComposition.cs
- Physical_oM/Physical_oM.csproj
- Structure_oM/Elements/Bar.cs
Closes #729 
see https://github.com/BHoM/BHoM_Engine/pull/1550
- Creation of `MaterialComposition` which stores a collection of `Material`s and their ratios
- Set `Physical.IFramingElement` as `IElementM`
- Set `Structure.Bar` as `IElementM`
> Dimensional_oM: Creation of the matter element IElementM

- Environment_oM/Gains/Ventilation.cs
Update Ventilation Object with ACH property
Closes #780
Added airchangerate property to the ventilation object
> Environment_oM: Updated Ventilation Object with AirChangeRate property

- Environment_oM/Environment_oM.csproj
- Environment_oM/Gains/Exhaust.cs
Closes #752 
Added exhaust object
> Environment_oM: Create Exhaust Object

- Environment_oM/Gains/Infiltration.cs
UpdatedInfiltrationGainObjectProperties
Closes #798 
Properties for Infiltration gain updated to reflect standard practice
> Environments_oM: Updated Infiltration Gain Object Properties

- Environment_oM/Environment_oM.csproj
- Environment_oM/Gains/Acoustics.cs
Add Acoustics Object
Closes #800
> Environment_oM: Add Acoustics Object

- BHoM.sln
- Spatial_oM/Properties/AssemblyInfo.cs
- Spatial_oM/Spatial_oM.csproj
Closes #806
Setting up new Spatial_oM
> Spatial_oM: Adding project

- Reflection_oM/Attributes/DeprecatedAttribute.cs
- Reflection_oM/Attributes/ReplacedAttribute.cs
- Reflection_oM/Attributes/ToBeDeletedAttribute.cs
- Reflection_oM/Attributes/ToBeRemovedAttribute.cs
- Reflection_oM/Reflection_oM.csproj
> Reflection_oM: Provide a distinction between deleted and replaced instead of deprecated

- MEP_oM/MEP_oM.csproj
- MEP_oM/Systems/Enums/PipeTypes.cs
> MEP_oM: Created Pipe Type Enum

- Structure_oM/Elements/IAreaElement.cs
Closes #809 
This PR assigns the interface to the appropriate objects (`IAreaElement` which will trickle down to the others, `FEMesh`, `Surface` and `Panel`)
see engine PR
https://github.com/BHoM/BHoM_Engine/pull/1683
> Structure_oM: Implement IElementM for Area elements

- MEP_oM/Equipment/AirHandlingUnit.cs
- MEP_oM/MEP_oM.csproj
- MEP_oM/Parts/AirHandlingUnit.cs
- MEP_oM/Parts/AirHandlingUnitBase.cs
> MEP_oM: Modified Air Handling Unit and Added AHU Part

- Diffing_oM/AECDeltas/DeltaPayload.cs
Closes #831 
Also raised #832 that will be done separately.
> Diffing_oM: added constructor to DeltaPayload class to fix serialisation error

- .github/CODEOWNERS
- Spatial_oM/Layouts/Enums/ReferencePoint.cs
- Spatial_oM/Layouts/ExplicitLayout.cs
- Spatial_oM/Layouts/ILayout2D.cs
- Spatial_oM/Layouts/LinearLayout.cs
- Spatial_oM/Layouts/MultiLinearLayout.cs
- Spatial_oM/Layouts/PerimeterLayout.cs
- Spatial_oM/Layouts/PerimiterLayout.cs
- Spatial_oM/Spatial_oM.csproj
Closes #758 
Adding initial 2D-layout objects. Initial use is for reinforcement, but intended to be usefull across more cases/disciplines as well.
Will create followup Engine PR that makes use of the classes
> Spatial_oM: Adding in inital 2D-layout objects

- CONTRIBUTING.md
- README.md
- docs/GOVERNANCE.md
Closes partially https://github.com/BHoM/admin/issues/4
- Update of README.md
- Update of CONTRIBUTING.md
- Update of GOVERNANCE.md
> Update README.md and docs

- Reflection_oM/Attributes/PreviousVersionAttribute.cs
Closes #848
Just make sure the names are matching. Another way to test is to make sure that `PreviousVersionAttribute` is now deserialising properly.
> Reflection_oM: Fix PreviousVersionAttribute constructor

- BHoM/FragmentSet.cs
See https://github.com/BHoM/BHoM_Engine/pull/1743 and https://github.com/BHoM/BHoM_UI/pull/253 for more details
> BHoM: Add a constructor from List for FragmentSet

- MEP_oM/MEP_oM.csproj
- MEP_oM/SpaceProperties/FireProtection.cs
> MEP_oM: Added Fire Protection Object

- Diffing_oM/StreamPointer.cs
See https://github.com/BHoM/BHoM_Engine/pull/1756 for more details
> Diffing_oM: Fix non-compliant constructor for StreamPointer

- Environment_oM/Environment_oM.csproj
- Environment_oM/Gains/Enums/ProfileDay.cs
- Environment_oM/Gains/Profile.cs
Closes #840 
To be tested in workflows by @cskinnerBH and @rboulton-BH
> Environment_oM: Revised Profile Object, Created ProfileDay, Revised ProfileType

- Architecture_oM/Elements/Floor.cs
- Architecture_oM/Elements/Roof.cs
- Architecture_oM/Elements/Wall.cs
- Geometry_oM/Surface/PlanarSurface.cs
- Physical_oM/Elements/Door.cs
- Physical_oM/Elements/Floor.cs
- Physical_oM/Elements/Roof.cs
- Physical_oM/Elements/Void.cs
- Physical_oM/Elements/Wall.cs
- Physical_oM/Elements/Window.cs
Closes #676 
Would recommend general project scripts as that is where I would expect things to go wrong, but that's also kind of expected.
Think the installer as a test should cover most issues
And don't really know what kind of test would be added otherwise.
> Geometry_oM: Make PlanarSurface IImmutable

- Environment_oM/Elements/Space.cs
> Environment_oM: Add space perimeter curve to Space object

- Environment_oM/Elements/Enums/OpeningType.cs
Closes #763 
Added Hole as an OpeningType in the OpeningType Enum
> Add Hole as OpeningType

- Environment_oM/Elements/Space.cs
- Environment_oM/Environment_oM.csproj
- Environment_oM/Ventilation/Ventilation.cs
Modify Space Object and Ventilation
https://github.com/BHoM/BHoM_Engine/issues/1791
Closes #882
> Environment_oM: Modify Space Object and Ventilation

- Environment_oM/Analysis/AnalysisGrid.cs
> Environment_oM: Fix AnalysisGrid for IImutability

- Environment_oM/Gains/Exhaust.cs
Closes #904 
Added ACH to exhaust object
> Environment_oM: Add ACH to Exhaust Object

- Reflection_oM/Output.cs
> Reflection_oM: Update output to allow larger number of outputs

- Spatial_oM/Spatial_oM.csproj
Closes #908 
Reflection_oM was referenced via dll in build folder, should be referenced via project reference
> Spatial_oM: Correct reference to Reflection_oM

- Common_oM/Common_oM.csproj
- Planning_oM/Construction/ConstructionPhase.cs
- Planning_oM/IPhase.cs
- Planning_oM/Planning_oM.csproj
Closes #885 
As description
Not needed
Won't be mergable until https://github.com/BHoM/BHoM_Engine/pull/1825 has been merged.
(which removes the unneeded create method)
> Common_oM: Move IPhase & ConstructionPhase to Planning_oM

- Acoustic_oM/Acoustic_oM.csproj
- Analytical_oM/Analytical_oM.csproj
- Architecture_oM/Architecture_oM.csproj
- BHoM/BHoM.csproj
- Common_oM/Common_oM.csproj
- Data_oM/Data_oM.csproj
- DeepLearning_oM/DeepLearning_oM.csproj
- Diffing_oM/Diffing_oM.csproj
- Dimensional_oM/Dimensional_oM.csproj
- Environment_oM/Environment_oM.csproj
- Geometry_oM/Geometry_oM.csproj
- Graphics_oM/Graphics_oM.csproj
- Humans_oM/Humans_oM.csproj
- LifeCycleAssessment_oM/LifeCycleAssessment_oM.csproj
- MEP_oM/MEP_oM.csproj
- Physical_oM/Physical_oM.csproj
- Planning_oM/Planning_oM.csproj
- Programming_oM/Programming_oM.csproj
- Quantities_oM/Quantities_oM.csproj
- Reflection_oM/Reflection_oM.csproj
- Spatial_oM/Spatial_oM.csproj
- Structure_oM/Structure_oM.csproj
This is part of https://github.com/BHoM/admin/issues/5
> Update post-builds 

- Analytical_oM/Analytical_oM.csproj
- Analytical_oM/Results/IResult.cs
- Analytical_oM/Results/IResultCollection.cs
- Analytical_oM/Versioning_32.txt
- Common_oM/Common_oM.csproj
- Environment_oM/Environment_oM.csproj
- Environment_oM/Results/Illuminance/Lux.cs
- Environment_oM/Results/Mesh/MeshElementResult.cs
- Environment_oM/Results/Mesh/MeshResult.cs
- Humans_oM/Humans_oM.csproj
- Humans_oM/ViewQuality/Results/ViewQualityResult.cs
- Structure_oM/Results/Bar Results/BarResult.cs
- Structure_oM/Results/Global Results/StructuralGlobalResult.cs
- Structure_oM/Results/Mesh/MeshElementResult.cs
- Structure_oM/Results/Mesh/MeshResult.cs
- Structure_oM/Results/Nodal Results/NodeResult.cs
- Structure_oM/Structure_oM.csproj
Closes #903 
Migrating IResult from Common_oM to Analytical_oM
This affects:
- Structure_oM
- Environments_oM
- Humans_oM
> BHoM: Migrate IResult to Analytical_oM

- Structure_oM/Requests/Enum/NodeResultType.cs
- Structure_oM/Results/Nodal Results/NodeModalMass.cs
- Structure_oM/Structure_oM.csproj
Closes #862 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Structure_oM/Issue862-AddNodeModalMassResult/NodeModalMass.gh?csf=1&web=1&e=3ONC4Q
> Structure_oM: Add Node Modal Mass Result

- LifeCycleAssessment_oM/Results/LifeCycleAssessmentResult.cs
Closes #925
See issue for details.
- This change doesn't affect anything else that the serialisation of this class. So I am happy to merge it this week.
- If you want to run the test I showed above, you will need the last installer and to compile the `Test_Toolkit`.
> LifeCycleAssessment_oM: Fix invalid constructor

- LifeCycleAssessment_oM/Enums/ProjectArea.cs
Closes #929 
Enum options reflect Carbon Leadership Forum baseline categories for m2. Previous versions were in ft and could cause confusion if utilising the benchmark functionality within the toolkit. 
For more details, please visit the [CLF Data Visualisation ](http://carbonleadershipforum.org/projects/embodied-carbon-benchmark-study-data-visualization/)
> LifeCycleAssessment_oM: Update ProjectArea Enum

- Data_oM/Requests/LogicalAndRequest.cs
- Data_oM/Requests/LogicalNotRequest.cs
- Data_oM/Requests/LogicalOrRequest.cs
> Data_oM: logical IRequest descriptions cleaned up

- Acoustic_oM/Elements/Room.cs
Closes #927 
Modified Acoustic Room object to include properties specified by Acoustics team
> Acoustic_oM: Modify Room Object

- Environment_oM/Gains/Enums/ProfileType.cs
- Environment_oM/Gains/Profile.cs
> Environment_oM: Revise ProfileType and ProfileDay

- Structure_oM/Requests/Enum/NodeResultType.cs
- Structure_oM/Results/Bar Results/BarDisplacement.cs
- Structure_oM/Results/Bar Results/BarModeShape.cs
- Structure_oM/Results/Bar Results/IBarDisplacement.cs
- Structure_oM/Results/Mesh/Enums/MeshResultType.cs
- Structure_oM/Results/Mesh/IMeshDisplacement.cs
- Structure_oM/Results/Mesh/MeshDisplacement.cs
- Structure_oM/Results/Mesh/MeshModeShape.cs
- Structure_oM/Results/Nodal Results/INodeDisplacement.cs
- Structure_oM/Results/Nodal Results/NodeModeShape.cs
- Structure_oM/Structure_oM.csproj
https://github.com/BHoM/BHoM_Engine/pull/1940
Closes #920
> Structure_oM: Added ModeShape result classes and IDisplacement classes

- Analytical_oM/Analytical_oM.csproj
- Analytical_oM/Elements/Graph.cs
- Data_oM/Collections/Graph.cs
- Data_oM/Collections/GraphLink.cs
- Data_oM/Data_oM.csproj
Closes #983 
~~Labelled 'parked' as further discussion may be needed. Would like to get general consensus on change to structure of `Graph<T>`, `GraphNode<T>` and `GraphLink<T.>` that this is intended to replace.~~
> Add Analytical Graph. Deprecate Graph, GraphNode and GraphLink

- Analytical_oM/Analytical_oM.csproj
- Analytical_oM/Elements/IRegion.cs
- Architecture_oM/Architecture_oM.csproj
- Architecture_oM/Elements/Room.cs
- Environment_oM/Elements/Space.cs
Closes #970
- Add IRegion interface
- Make Environments Space implement new interface
- Make Architectual Room implement interface
> Analytical_oM: Add IRegion interface

- Structure_oM/Results/Global Results/ModalDynamics.cs
Closes #998 
Fixes the Modal dynamics constructor. Before assigned property to itself.
> Structure_oM: Fix ModalDynamics constructor

- Programming_oM/Nodes/BlockNode.cs
- Programming_oM/Nodes/LoopNode.cs
Closes #1027
See issue for details
> Programming_oM: Remove dependency to GetShallowClone

- Architecture_oM/Architecture_oM.csproj
- Architecture_oM/Elements/Ceiling.cs
- Architecture_oM/Elements/CeilingTile.cs
Closes #1029 
Facilitating BHoM/BHoM_Engine#2049 by creating a ceiling tile object.
> Architecture_oM: Add ceiling tile object

- MEP_oM/Elements/VolumeDamper.cs
- MEP_oM/MEP_oM.csproj
Closes #1008 
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/MEP_oM/MEP_oM-%231008_VolumeDamper.gh?csf=1&web=1&e=tYrdks)
- Object Creation
> MEP_oM: Creation of VolumeDamper Object

- Graphics_oM/Render/RenderMesh.cs
- Graphics_oM/Render/RenderMeshOptions.cs
Closes #1046 
See TriangleNet.
> Graphics_oM: Make RenderMesh a Fragment

- Humans_oM/Employee.cs
Closes #1051 
Closes #1052 
As title. Needed to remove usages of CustomData in some Toolkit.
> Humans_oM: Adding "Manager" property to Employee; added descriptions

- LifeCycleAssessment_oM/ScopeObjects/ElectricalScope.cs
- LifeCycleAssessment_oM/ScopeObjects/FireProtectionScope.cs
- LifeCycleAssessment_oM/ScopeObjects/MechanicalScope.cs
- LifeCycleAssessment_oM/ScopeObjects/PlumbingScope.cs
Addition of MEP scope object inputs. Inputs are in order of perceived importance/weight for LCA related factors.
Additional objects input allows for objects that potentially won't be BHoM specific types (eg filters, hangers, brackets)
Closes #1043
> LifeCycleAssessment_oM: Modification of MEP Scope Object

- MEP_oM/Elements/CommercialFixtureUsage.cs
- MEP_oM/Elements/IFixtureFlow.cs
- MEP_oM/Elements/IFixtureUsage.cs
- MEP_oM/Elements/PlumbingFixtureFlow.cs
- MEP_oM/Elements/ResidentialFixtureUsage.cs
- MEP_oM/MEP_oM.csproj
Closes #1058 
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ClimateEmergency_Toolkit/RemoveMethods.gh?csf=1&web=1&e=nQl2Vp)
- Additional properties added to Occupancy within Architecture_oM
- `IFixtureFlow` created
- `IFixtureUsage` created
- `CommercialFixtureUsage` and `ResidentialFixtureUsage` created
- `PlumbingFixtureFlow` created
> MEP_oM: Support for ClimateEmergency Methods

- MEP_oM/Elements/LightFixture.cs
- MEP_oM/MEP_oM.csproj
Addition of Light Fixture object for MEP.
@enarhi happy to add more properties if it suits the purpose of specialists as well!
Closes #1010
> MEP_oM: Addition of Light Fixture Object

- Reflection_oM/Attributes/PreviousInputNames.cs
- Reflection_oM/Reflection_oM.csproj
Support https://github.com/BHoM/BHoM_UI/pull/330
Provides new attribute needed for https://github.com/BHoM/BHoM_UI/pull/330
See https://github.com/BHoM/BHoM_UI/pull/330
> Reflection_oM: Improved name change support on method arguments

- .github/CODEOWNERS
- BHoM.sln
- Test_oM/Properties/AssemblyInfo.cs
- Test_oM/Results/Enums/InputOutputComparisonDiffingType.cs
- Test_oM/Results/Enums/InputOutputComparisonType.cs
- Test_oM/Results/InputOutputComparison.cs
- Test_oM/Results/InputOutputComparisonDiffing.cs
- Test_oM/Results/InputOutputComparisonSummary.cs
- Test_oM/Results/InputOutputDifference.cs
- Test_oM/Test_oM.csproj
- Test_oM/UnitTests/TestData.cs
- Test_oM/UnitTests/UnitTest.cs
Fixes #1076 
Code moved verbatim, no changes made other than copyright and compliance.
> Test_oM: Return Test_oM to BHoM

- Reflection_oM/Debugging/Event.cs
https://github.com/BHoM/BHoM_UI/pull/336
See https://github.com/BHoM/BHoM_UI/pull/336
> Reflection_oM: Add UTC time to events

- Structure_oM/Constraints/LinkConstraint.cs
- Structure_oM/Elements/RigidLink.cs
Closes #1101 
Alignes the descriptions with changes made in https://github.com/BHoM/BHoM/pull/961
> Structure_oM: Update LinkConstraint descriptions to Primary/Secondary nomenclature

- BHoM.sln
- Lighting_oM/Analysis/AnalysisGrid.cs
- Lighting_oM/Analysis/Node.cs
- Lighting_oM/Elements/Enums/MountingType.cs
- Lighting_oM/Elements/Luminaire.cs
- Lighting_oM/Elements/LuminaireType.cs
- Lighting_oM/Lighting_oM.csproj
- Lighting_oM/Properties/AssemblyInfo.cs
- Lighting_oM/Results/Illuminance/Lux.cs
- Lighting_oM/Results/Mesh/MeshElementResult.cs
- Lighting_oM/Results/Mesh/MeshResult.cs
Closes #993 
Addition of Lighting_oM with base objects.
> Lighting_oM: Initial Creation

- Environment_oM/Elements/Enums/PanelType.cs
Closes #1106 
Adds Adiabatic Enum to PanelType
> Environment_oM: Add Adiabatic Enum to PanelType

- MEP_oM/System/CableTray.cs
- MEP_oM/System/SectionProperties/CableTraySectionProperty.cs
- MEP_oM/System/SectionProperties/DuctSectionProperty.cs
- MEP_oM/System/SectionProperties/PipeSectionProperty.cs
- MEP_oM/System/SectionProperties/WireSectionProperty.cs
Closes #1064 
Closes #1086 
[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/MEP_oM/MEP_oM-%231064%20MEPMaterials.gh?csf=1&web=1&e=PXC2UR)
> MEP_oM: Compliance updates for matter-based workflows

- Test_oM/Results/Enums/ResultStatus.cs
- Test_oM/Results/TestResult.cs
- Test_oM/Test_oM.csproj
Provide support for closing https://github.com/BHoM/BHoM_Engine/issues/2221
Used by those two PRs: 
- https://github.com/BHoM/Test_Toolkit/pull/307
- https://github.com/BHoM/BHoM_Engine/pull/2222
@FraserGreenroyd , as discussed this is mostly a port from the `CodeComplianceTest_oM` with some modifications to make it more generic.
> Test_oM: Add TestResult and ResultStatus classes

- COPYRIGHT_HEADER.txt
> BHoM: Update Copyright_Header.txt file to reflect new year

- core.txt
Fixes #1146 
Ensure Azure CheckCore passes.
> CI/CD: Fix CheckCore core.txt file

- BHoM/BHoM.csproj
- BHoM/Interface/ISpecification.cs
Closes #1144
The specification interface defines a soon-to-be core concept in BHoM used for [object specification](https://github.com/CIHDigitalConfigurator/CIH_Toolkit) definition. 
Not needed.
> BHoM: Created ISpecification interface

- LifeCycleAssessment_oM/Results/GlobalWarmingPotentialResult.cs
Closes #1163 
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/LifeCycleAssessment_Toolkit/%23188-MultiQT.gh?csf=1&web=1&e=JSuSxF)
> LifeCycleAssessment_oM: Make GWP Results settable

- MEP_oM/Enums/DamperType.cs
- MEP_oM/Enums/ElectricalEquipmentType.cs
- MEP_oM/Enums/ElectricalFixtureType.cs
- MEP_oM/Enums/FireAlarmDeviceType.cs
- MEP_oM/Enums/PlumbingFixtureType.cs
- MEP_oM/Enums/ValveType.cs
- MEP_oM/Equipment/ElectricalEquipment.cs
- MEP_oM/Equipment/MechanicalEquipment.cs
- MEP_oM/Fixtures/AirTerminal.cs
- MEP_oM/Fixtures/ElectricalFixture.cs
- MEP_oM/Fixtures/FireAlarmDevice.cs
- MEP_oM/Fixtures/LightFixture.cs
- MEP_oM/Fixtures/PlumbingFixture.cs
- MEP_oM/Fragments/PlumbingFlowFragment.cs
- MEP_oM/Fragments/PlumbingLoadingFixtureUnitFragment.cs
- MEP_oM/MEP_oM.csproj
- MEP_oM/System/Dampers/Damper.cs
- MEP_oM/System/Dampers/VolumeDamper.cs
- MEP_oM/System/Node.cs
- MEP_oM/System/Valves/Valve.cs
Closes #1112 
@Hmullerjones if you could review for UK understanding (receptacle vs socket, isolator vs disconnect) I tried to cover both when possible
> MEP_oM: Add point-based MEP objects

- Inspection_oM/Audit.cs
- Inspection_oM/Issue.cs
Closes #1167 
Files are not required for testing. To test, create issue object and check the new properties `DateClosed` and `AuditID` are present
Added 2 new properties to Issue object.
> Inspection_oM: Added two new properties to Issues

- Facade_oM/Elements/FrameEdge.cs
> Facade_oM: Added IElementM to FrameEdge

- Environment_oM/Configuration/OpeningOption.cs
- Environment_oM/Environment_oM.csproj
Fixes #1210 
[Available here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Environment_oM/%231213-OpeningConfigurations/OpeningConfigurations.gh?csf=1&web=1&e=IUp0Gv)
> Environment_oM: Add opening configuration object

- MEP_oM/System/MaterialFragments/DuctMaterial.cs
- MEP_oM/System/MaterialFragments/PipeMaterial.cs
- MEP_oM/System/MaterialFragments/WireMaterial.cs
~~Beginning to resolve~~ Fixes #1158
> MEP_oM: Ensure materials implement correct interface

- LifeCycleAssessment_oM/LifeCycleAssessment_oM.csproj
- LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
Closes #1187 
[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/LifeCycleAssessment_oM/%231187-ProjectLCA.gh?csf=1&web=1&e=0X5bgZ)
> LifeCycleAssessment_oM: Creation of ProjectLifeCycleAssessmentResults

- Environment_oM/Configuration/OpeningOption.cs
Fixes #1217 
[Here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Environment_oM/%231218-OpeningTYpe?csf=1&web=1&e=XIhF7P)
> Environment_oM: Update opening option to include opening type

- Structure_oM/SurfaceProperties/Enums/LoadPanelSupportConditions.cs
Closes #1196
[Test File](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%2FStructure%5FoM%2F%231196%20%2D%20Add%20auto%20to%20LoadPanelSupportConditions%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%2FStructure%5FoM)
> Structure_oM: Add Auto Option to LoadPanelSupportConditions

- Humans_oM/ViewQuality/CvalueFocalMethodEnum.cs
- Humans_oM/ViewQuality/CvalueSettings.cs
Closes 
#951 
https://github.com/BHoM/BHoM/issues/1073
https://github.com/BHoM/BHoM_Engine/issues/2137
> Humans_oM: Refactor to c value objects

- Structure_oM/Loads/ContourLoadSet.cs
- Structure_oM/Loads/UniformLoadSet.cs
- Structure_oM/Loads/UniformLoadSetRecord.cs
- Structure_oM/Structure_oM.csproj
- Structure_oM/Versioning_42.json
> Structure_oM: Adding UniformLoadSet and ContourLoadSet from RAM_oM

- BHoM/BHoM.csproj
- BHoM/Interface/ISettings.cs
See https://github.com/BHoM/BHoM_UI/pull/394 for more details
> Migrate ISettings to the oM.Base namespace

- Diffing_oM/Diffing_oM.csproj
- Facade_oM/Facade_oM.csproj
> BHoM: Fix root namespaces for Diffing and Facade oMs

- Structure_oM/MaterialFragments/Timber.cs
> Structure_oM: Add timber design values to the Timber MaterialFragment class

- BHoM/Enumeration.cs
Closes #1324
See issue
No need
> Base_oM: Adding missing virtual keyword on Enumeration properties

- Spatial_oM/ShapeProfiles/TaperFlangeChannelProfile.cs
- Spatial_oM/ShapeProfiles/TaperFlangeISectionProfile.cs
Closes #512 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Spatial_oM/%231316-add-tapered-flange-sections?csf=1&web=1&e=aMhwGq
> Spatial_oM: Add support for tapered flange sections

- Structure_oM/SurfaceProperties/Layer.cs
- Structure_oM/SurfaceProperties/Layered.cs
> Added Layer and Layered surface property

- Analytical_oM/Results/IMeshElementResult.cs
- Analytical_oM/Results/IMeshResult.cs
- Structure_oM/Results/Bar Results/IBarDisplacement.cs
- Structure_oM/Results/IStructuralResult.cs
- Structure_oM/Results/Mesh/IMeshDisplacement.cs
- Structure_oM/Results/Mesh/MeshResult.cs
- Structure_oM/Results/Nodal Results/INodeDisplacement.cs
> Analytical_oM: Refresh of Result interfaces

- Environment_oM/Elements/Enums/PanelType.cs
Closes #1334 
Added a TranslucentShade panel type.
> Environment_oM: TranslucentShade panel type

- Analytical_oM/Results/ResultFilter.cs
- Graphics_oM/Colours/Gradient.cs
- Graphics_oM/Colours/GradientOptions.cs
- Graphics_oM/Colours/IGradient.cs
- Graphics_oM/Colours/SteppedGradient.cs
- Structure_oM/Results/Bar Results/BarDeformation.cs
- Structure_oM/Results/Bar Results/IBarDisplacement.cs
- Structure_oM/Results/Global Results/GlobalReactions.cs
- Structure_oM/Results/IDisplacement.cs
- Structure_oM/Results/IReaction.cs
- Structure_oM/Results/Nodal Results/NodeReaction.cs
Closes #1366
- Adding SteppedGradient in support of visualisation methods in Results_Engine.
- Adding some basic interfaces in structure namespace for results containing the same properties.
> Graphics_oM: Result display improvements

- Analytical_oM/Results/IElement1DResult.cs
- Analytical_oM/Results/IMeshElementResult.cs
- Analytical_oM/Results/IObjectResult.cs
- Analytical_oM/Results/IResultSeries.cs
- Analytical_oM/Results/ResultFilter.cs
- Structure_oM/Results/Bar Results/BarDisplacement.cs
- Structure_oM/Results/Bar Results/BarForce.cs
- Structure_oM/Results/Bar Results/BarModeShape.cs
- Structure_oM/Results/Bar Results/BarRequiredArea.cs
- Structure_oM/Results/Bar Results/BarStrain.cs
- Structure_oM/Results/Bar Results/BarStress.cs
- Structure_oM/Results/Bar Results/CompositeUtilisation.cs
- Structure_oM/Results/Bar Results/IBarDisplacement.cs
- Structure_oM/Results/Bar Results/SteelUtilisation.cs
- Structure_oM/Results/Global Results/ModalDynamics.cs
- Structure_oM/Results/IDisplacement.cs
- Structure_oM/Results/IReaction.cs
- Structure_oM/Results/Mesh/IMeshDisplacement.cs
- Structure_oM/Results/Mesh/MeshForce.cs
- Structure_oM/Results/Mesh/MeshRequiredArea.cs
- Structure_oM/Results/Mesh/MeshStress.cs
- Structure_oM/Results/Mesh/MeshVonMises.cs
- Structure_oM/Results/Nodal Results/INodeDisplacement.cs
- Structure_oM/Results/Nodal Results/NodeAcceleration.cs
- Structure_oM/Results/Nodal Results/NodeDisplacement.cs
- Structure_oM/Results/Nodal Results/NodeModalMass.cs
- Structure_oM/Results/Nodal Results/NodeModeShape.cs
- Structure_oM/Results/Nodal Results/NodeVelocity.cs
> Analytical_oM: Add IResultSeries interface

- Graphics_oM/Render/RenderCurve.cs
fixes part of #1271 
Adding RenderCurve class to display curve with line thickness.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Graphics_oM/Graphics_oM-%231271-AddRenderCurve?csf=1&web=1&e=Uvpn7O
> Graphics_oM: Adding RenderCurve class

- Geometry_oM/Surface/PlanarSurface.cs
Closes #426
Making PlanarSurface implement IElement2D
See engine PR
> Geometry_oM: Adding IElement2D interface to the PlanarSurface

- Acoustic_oM/Acoustic_oM.csproj
- Analytical_oM/Analytical_oM.csproj
- Architecture_oM/Architecture_oM.csproj
- BHoM/BHoM.csproj
- Data_oM/Data_oM.csproj
- DeepLearning_oM/DeepLearning_oM.csproj
- Diffing_oM/Diffing_oM.csproj
- Dimensional_oM/Dimensional_oM.csproj
- Environment_oM/Environment_oM.csproj
- Facade_oM/Facade_oM.csproj
- Geometry_oM/Geometry_oM.csproj
- Graphics_oM/Graphics_oM.csproj
- Humans_oM/Humans_oM.csproj
- Inspection_oM/Inspection_oM.csproj
- LifeCycleAssessment_oM/LifeCycleAssessment_oM.csproj
- Lighting_oM/Lighting_oM.csproj
- MEP_oM/MEP_oM.csproj
- Physical_oM/Physical_oM.csproj
- Planning_oM/Planning_oM.csproj
- Programming_oM/Programming_oM.csproj
- Quantities_oM/Quantities_oM.csproj
- Security_oM/Security_oM.csproj
- Spatial_oM/Spatial_oM.csproj
- Structure_oM/Structure_oM.csproj
- Test_oM/Test_oM.csproj
- Versioning_oM/Versioning_oM.csproj
Update Assembly Information to include description
> Update Assembly Information

- BHoM/Attributes/DisplayTextAttribute.cs
Closes #1440 
See issue for description.
See Engine PR: https://github.com/BHoM/BHoM_Engine/pull/2930
> New DisplayText attribute

- BHoM/Reflection/UnderlyingType.cs
- BHoM/System/UnderlyingType.cs
- BHoM/Versioning_60.json
> BHoM: Move UnderlyingType to a sub folder

- LifeCycleAssessment_oM/Enums/QuantityType.cs
Closes https://github.com/BHoM/LifeCycleAssessment_Toolkit/issues/284
By inspection
> LifeCycleAssesment_oM: Add eNum for Energy on Quantity Type for EnviromentalProductDeclaration

- LifeCycleAssessment_oM/Results/EnvironmentalMetricResult.cs
Closes #1446 
Simply adding IResultItem interface to EnvironmentalMetricResult, which was implicit from IObjectResult before https://github.com/BHoM/BHoM/pull/1379
> LifeCycleAssesment_oM: Add IResultItem to EnvironmentalMetricResult

- Environment_oM/Versioning_61.json
> Environment_oM: Add Versioning file for MachineLearning Toolkit removal

- Environment_oM/Elements/Mesh.cs
- Environment_oM/Versioning_61.json
Closes #1473  (Even though the author did not tell us what to fix)
Not required for the spelling update as no changes to functionality were introduced.
> Environment_oM: Update spelling for BounderyZones

- Physical_oM/Elements/MeshElement.cs
Closes #1455 
Not required here. Just code inspection
> Physical_oM: Adding IElement and IPhysical interfaces to MeshElement

- Dimensional_oM/IElement3D.cs
> Dimensional_oM: Adding IElement3D

- BHoM/Interface/IFragment.cs
Closes #1277 
Adding a description as discussed and proposed in issue.
> Base_oM: Add Description To IFragment

- BHoM/Interface/IContainer.cs
> Base_oM: add `IContainer` interface

- BHoM/Attributes/Enums/UIExposure.cs
- BHoM/Attributes/InputAttribute.cs
Fixes #1482 
Happy to discuss naming of the object - this is a first pass.
> BHoM: Add UIExposure enum and add to InputAttribute enum

- Analytical_oM/IAnalytical.cs
- Analytical_oM/Results/Attributes/IdentifierAttribute.cs
- BHoM/Attributes/FilePathAttribute.cs
- BHoM/Attributes/FolderPathAttribute.cs
- BHoM/Attributes/InputClassificationAttribute.cs
- BHoM/Attributes/UniqueAttribute.cs
- BHoM/Interface/IEnum.cs
- BHoM/Interface/IOutput.cs
- DeepLearning_oM/IModule.cs
- DeepLearning_oM/IShape.cs
- DeepLearning_oM/Optimisers/IOptimiser.cs
- Facade_oM/IProperty.cs
- Programming_oM/Nodes/INode.cs
- Programming_oM/Params/INodeParam.cs
- Structure_oM/IProperty.cs
> BHoM: Add IObject interface to objects as required

- Structure_oM/Requests/Enum/GlobalResultType.cs
- Structure_oM/Requests/Enum/NodeResultType.cs
- Structure_oM/Results/Global Results/ModalDynamics2.cs
- Structure_oM/Results/Global Results/ModalMassAndFrequency.cs
- Structure_oM/Results/Nodal Results/ModalResultNormalisation.cs
- Structure_oM/Results/Nodal Results/NodeModalResults.cs
Closes #1471
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Structure_oM/%231521-AddUpdatedStructuralDynamicsResults?csf=1&web=1&e=OeKgWS
- Add new NodeModalResult class combining eigenvector and node modal mass
- Add new FrequencyAndMass global result, giving back the total modal mass in all directions as well as Frequency
> Structure_oM: Add updated structural dynamics results

- Dimensional_oM/IElement0D.cs
- Dimensional_oM/IElement1D.cs
- Dimensional_oM/IElement2D.cs
- Dimensional_oM/IElementM.cs
Closes #1529 
- updated URL inside DocumentationURL for IElement0D, IElement1D, IElement2D, and IElementM
> Dimensional_oM: Updated URL to DocumentationURL

- Structure_oM/Elements/Bar.cs
Closes #1530
- Updated URL inside DocumentationURL
> Structure_oM: Updated DocumentationURL

- BHoM/Attributes/ClassificationAttribute.cs
- BHoM/Attributes/FilePathAttribute.cs
- BHoM/Attributes/InputAttribute.cs
- BHoM/Attributes/MultiOutputAttribute.cs
- BHoM/Attributes/OutputAttribute.cs
Closes #1528
Descriptions only.
> Base_oM: attribute descriptions added

- .ci/BHoMBot/Nuget/BHoM.nuspec
> BHoM: Add nuspec template file

- BHoM.sln
- Ground_oM/Ground_oM.csproj
Closes #1548 
CI/CD
- Added Ground_oM for future development planned in 6.4 milestone
> Ground_oM: Add initial commit for oM

- Physical_oM/Elements/PadFoundation.cs
- Physical_oM/Elements/Pile.cs
- Physical_oM/Elements/PileFoundation.cs
Closes #566
Closes #1155
Just object creation.
> Physical_oM: foundation objects added

- CONTRIBUTING.md
- Structure_oM/Elements/Bar.cs
- Structure_oM/Elements/Pile.cs
> BHoM: Documentation Link updates

- Structure_oM/Loads/Enums/LoadType.cs
> Structure_oM: Rename PointForce to PointLoad

- Diffing_oM/AECDeltas/DeltaPayload.cs
- Diffing_oM/Delta.cs
- Diffing_oM/DiffingConfig.cs
- Diffing_oM/Revision.cs
- Diffing_oM/StreamPointer.cs
- Diffing_oM/Versioning_71.json
> Diffing_oM: Rename Id to ID as appropriate

- Structure_oM/SurfaceProperties/BuiltUpRibbed.cs
- Structure_oM/SurfaceProperties/Cassette.cs
Closes #1601
- Add new Cassette Surface property
- Add new BuiltUpRibbed surface property
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Structure_oM/%231604-AddCassetteAndBuiltUpRibProperties?csf=1&web=1&e=0MwLH7
> Structure_oM: Add cassette and built up rib properties

- BHoM/BHoM.csproj
> BHoM: Add mkdir command for Developer folder

- Acoustic_oM/Acoustic_oM.csproj
- Analytical_oM/Analytical_oM.csproj
- Architecture_oM/Architecture_oM.csproj
- BHoM/BHoM.csproj
- Data_oM/Data_oM.csproj
- DeepLearning_oM/DeepLearning_oM.csproj
- Diffing_oM/Diffing_oM.csproj
- Dimensional_oM/Dimensional_oM.csproj
- Environment_oM/Environment_oM.csproj
- Facade_oM/Facade_oM.csproj
- Geometry_oM/Geometry_oM.csproj
- Graphics_oM/Graphics_oM.csproj
- Ground_oM/Ground_oM.csproj
- Humans_oM/Humans_oM.csproj
- Inspection_oM/Inspection_oM.csproj
- LifeCycleAssessment_oM/LifeCycleAssessment_oM.csproj
- Lighting_oM/Lighting_oM.csproj
- MEP_oM/MEP_oM.csproj
- Matter_oM/Matter_oM.csproj
- Physical_oM/Physical_oM.csproj
- Planning_oM/Planning_oM.csproj
- Programming_oM/Programming_oM.csproj
- Quantities_oM/Quantities_oM.csproj
- Search_oM/Search_oM.csproj
- Security_oM/Security_oM.csproj
- Spatial_oM/Spatial_oM.csproj
- Structure_oM/Structure_oM.csproj
- Test_oM/Test_oM.csproj
- Versioning_oM/Versioning_oM.csproj
Update AssemblyFileVersion to 7.3
Remove previous version attributes
> Update AssemblyFileVersion to 7.3

- Verification_oM/Results/SpecificationResult.cs
Closes #1647
See https://github.com/BHoM/BHoM_Engine/pull/3431
> Verification_oM: SpecificationResult made immutable

- Verification_oM/Results/Conditions/IsNotNullResult.cs
- Verification_oM/Results/Conditions/IsOfTypeResult.cs
- Verification_oM/Results/Conditions/LogicalCollectionConditionResult.cs
- Verification_oM/Results/Conditions/SingleLogicalConditionResult.cs
- Verification_oM/Results/Conditions/ValueConditionResult.cs
> Verification_oM: Code compliance fixed

- Verification_oM/Results/RequirementResult.cs
> Verification_oM: compliance fixed

- Physical_oM/Constructions/Layer.cs
> Physical_oM fixed missing unit attribute

- Verification_oM/Conditions/HasValue.cs
Closes #
See https://github.com/BHoM/BHoM_Engine/pull/3460
> Verification_oM: HasValue condition added

- Quantities_oM/Attributes/AirPermeability.cs
- Quantities_oM/Attributes/SoundPressureLevel.cs
- Quantities_oM/Attributes/ThermalTransmittance.cs
- Quantities_oM/Attributes/WeightedSoundReductionIndex.cs
Closes #1660
Add quantities required for dKoP
> Quantities required for dKoP added

- Security_oM/Elements/CameraDevice.cs
Closes #
Security_oM: Change Horizontal Field of view property to angle property to allow angles bigger than 180 degrees
> Security_oM: Change Horizontal Field of view property to angle property

- Versioning_oM/Attributes/DowngraderAttribute.cs
- Versioning_oM/Attributes/UpgraderAttribute.cs
- Versioning_oM/Attributes/VersioningTargetAttribute.cs
- Versioning_oM/NoUpdateException.cs
https://github.com/BHoM/Versioning_Toolkit/pull/302
See PR above for details
> Refactoring of the versioning toolkit

- Verification_oM/Results/RequirementResult.cs
Closes #
See https://github.com/BHoM/BHoM_Engine/pull/3516
> Verification_oM: events property added to RequirementResult
