BHoM/BHoM

Reflection_oM/Output.cs

Fixes #301
`Output<>` no longer inheriting from BHoMObject, but intead only IObject.
Should not have any affect on the current functionalities of the UI. Reason for change is that initialising BHoMObjects can be a bit slow, while performing iterative algorithms that relies on calling a method that has an `Output<>` as a return type. Som initial testing showed that for a simple distance method, the change made here can make the method run approximately 5 times faster.

Outputs to imploement IObject instead of inheriting BHoMObject

---

Environment_oM/Enums/Materials/GasType.cs
Environment_oM/Environment_oM.csproj

Fixes #404 
Adds gas types as requested.
N/A
- Add Gas Type enum and `GasType` property to `MaterialPropertiesGas`
I enjoyed that this issue was #404 - with missing gas types... gave me a chuckle!

Error 404 - Gas Types not found

---

Geometry_oM/CoordinateSystem/Cartesian.cs
Structure_oM/Elements/Node.cs

Closes #267 
Changing the Node class in the `Structure_oM` from owning a `Point` to a `CoordinateSystem.Cartesian`.
Name for this property updated from `Position` to `Coordinates`
**Please note that this will invalidate any serialised Node and Bar objects!**
- `Node` class property `Position` renamed to `Coordinates` and type changed from `Point` to `CoordinateSystem.Cartesian` #267 
- Explicit casting from `CoordinateSystem.Cartesian` to `Node`
- Explicit casting from `Point` to `CoordinateSystem.Cartesian`
Changes made include breaking changes for other toolkits. Please do not merge until dependant PR's are raised and approved

Structure o m issue267 nodes to own a cartesian coordinate system

---

Structure_oM/Elements/FramingElement.cs

Closes #331
Framingelement LocationCurve from Line to ICurve.
@ZiolkowskiJakub FYI, could you have a look into how this affects Revit_Toolkit? This needs to be assessed before merging.
Please check that any communication with Revit is not broken!
- FramingElement updated to carry an ICurve instead of a Line

FramingElement LocationCurve to ICurve

---

Structure_oM/Elements/FEMesh.cs

Closes #449 
Adds IAreaElement interface to FEMesh object.
https://burohappold.sharepoint.com/:f:/s/BHoM/EhclvxYWIMhKqDKO5wpiDaMB_DZY42ae63L4paYIyWxinw?e=S3BPXQ
Area loads can be applied to FEMesh objects.

Structure_oM: Closes #449 FEMesh to Inherit IAreaElement interface

---

Geometry_oM/Geometry_oM.csproj
Geometry_oM/Solid/BoundaryRepresentation.cs
Geometry_oM/Solid/Cone.cs
Geometry_oM/Solid/Cuboid.cs
Geometry_oM/Solid/Cylinder.cs
Geometry_oM/Solid/ISolid.cs
Geometry_oM/Solid/Sphere.cs
Geometry_oM/Solid/Torus.cs

Closes #453
Closes #454
Closes #455 
Creation of initial Solid Geometry representations in the BH.oM.Geometry namespace. As mentioned in the referenced Issues - this will for the immediate term be for representation in BHoM and translation between external libraries and platforms. Beyond Converts, Engine methods will necessarily be kept to a minimum.

Geometry_oM #453 add initial solid geometry representations

---

Geometry_oM/Misc/BoundingBox.cs

Closes #497
The UI breaks when the operator is called with null arguments. I will treat it in the UI as well, but even if this may be a little forced, I think it is safer to add null checks here.

Issue497-BoundindBoxOperatorNullCheck

---

Geometry_oM/Geometry_oM.csproj
Geometry_oM/Interface/IElement.cs
Geometry_oM/Interface/IElement0D.cs
Geometry_oM/Interface/IElement2D.cs

Closes #503 
No test file needed.
- `IElement` parent interface for `IElement0D`, `IElement1D` and `IElement2D` added to allow the methods work on objects having different number of dimensions

Geometry_oM-Issue503-CreateIElementParentInterface

---

Architecture_oM/Architecture_oM.csproj
Architecture_oM/Elements/Floor.cs
Architecture_oM/Elements/Roof.cs
Architecture_oM/Elements/Wall.cs
Common_oM/Common_oM.csproj
Common_oM/Interface/IObject2D.cs
Common_oM/Materials/Material.cs
Common_oM/Materials/MaterialEnums.cs
Common_oM/Properties/CompoundLayer.cs
Common_oM/Properties/Object2DProperties.cs
Reflection_oM/Attributes/DeprecatedAttribute.cs
Structure_oM/Elements/FramingElement.cs
Structure_oM/FramingProperties/ConstantFramingElementProperty.cs
Structure_oM/FramingProperties/IFramingElementProperty.cs

Closes #494 
Closes #467 
Closes #466 
Closes #465 
Closes #460 
Closes #495 
Deprecating classes being superseded by new classes in the Physical_oM
Expanded the DeprecatedTag targets to interface and enum as well to be able to deprecate certain files.
**Please to not merge until Revit and Engine is ready!**
See testfiles for engine/Revit. This is removing old functionality rather than adding new, so 
- BH.oM.Structure.Elements.FramingElement
- BH.oM.Structure.FramingProperties.ConstantFramingElementProperty
- BH.oM.Structure.FramingProperties.IFramingElementProperty
- BH.oM.Common.Materials.Material
- BH.oM.Common.Materials.MaterialType
- BH.oM.Common.Interface.IObject2D
- BH.oM.Common.Properties.CompoundLayer
- BH.oM.Common.Properties.Object2DProperties
- …

Structure common architecture o m issue494 physical cleanup

---

Architecture_oM/Architecture_oM.csproj
Architecture_oM/Elements/Room.cs

Fixes #389 
N/A see files changed
This adds a basic `Room` object for MEP/Energy modelling with @kayleighhoude to begin the workflows around rooms.
The object will need further expansion later but this is to begin prototyping up the workflows.

Add Room object to Architecture oM

---

Environment_oM/Climate/IClimateObject.cs
Environment_oM/Climate/Location.cs
Environment_oM/Climate/SpaceTime.cs
Environment_oM/Climate/Sun.cs
Environment_oM/Climate/SunPosition.cs
Environment_oM/Environment_oM.csproj

Fixes #542 
N/A
- Added SpaceTime Climate object
- Added Location Climate object
- Added Sun Climate object
- Added `Climate` to `BH.oM.Environment` namespace
This begins the work of centralising some of our climate objects which may be useful in toolkits such as the @BHoM/climateemergency_toolkit , etc.

Environment_oM: Add Climate objects

---

Architecture_oM/Elements/Grid.cs
Architecture_oM/Elements/Level.cs
Geometry_oM/Geometry_oM.csproj
Geometry_oM/SettingOut/Grid.cs
Geometry_oM/SettingOut/Level.cs

Closes #536 
`BH.oM.Architecture.Elements.Grid` and `Level` deprecated.
`Grid` and `Level` added to `BH.oM.Geometry.SettingOut`

Migrate Grids and Levels from Architecture to Geometry.SettingOut

---

BHoM/Interface/IBHoMFragment.cs

Closes #563 
As agreed with @adecler, @al-fisher which asked me to action this (also, see discussion in https://github.com/BHoM/BHoM/issues/537):
changed IBHoMFragment to inherit IObject instead of IBHoMObject.
This allows to implement "lighter" fragments in all cases where the BHoMObject properties are not needed.
- Changed IBHoMFragment to implement IObject instead of IBHoMObject.

BHoM: Fragments to be `IObject` instead of `IBHoMObject`

---

BHoM/BHoM.csproj
BHoM/BHoMObject.cs
BHoM/FragmentSet.cs
BHoM/Interface/IBHoMObject.cs
Diffing_oM/HashFragment.cs

Closes #573 
See also the discussion in #538 (Closes #538).
The FragmentSet class allows only `IBHoMFragment` types to be stored in the set (`where T : IBHoMFragment` ). 
The set therefore can include only one type of the same Fragment.
The FragmentSet has a method `GetKeyForItem` which returns the `Type` for a specific Fragment, that is the key of the collection. That is the only method that absolutely must be overridden, because without it the KeyedCollection cannot extract the keys from the items. See https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.keyedcollection-2?view=netframework-4.8
This has several effects:
- Compliance: Fragments now actually reflect their intended nature of an [Entity Component …

Fragments in BHoMObject now stored in a FragmentSet instead of in a List

---

README.md

Legacy installer hyperlink is updated to http://bhom.xyz

Update the README installer link

---

Structure_oM/Requests/GlobalResultRequest.cs
Structure_oM/Requests/NodeResultRequest.cs
Structure_oM/Structure_oM.csproj

Closes #608 
Renaming Query to Request
Adding LoadAxis to NodeResultRequest
- Renaming Query to Request For NodeResultRequest and GlobalResultRequest
- Adding LoadAxis to NodeResultRequest
These classes was just added and are not in use anywhere yet. As aiming to start making use of them this sprint, would be good if this could be closed out and merged ASAP.
FYI @JosefTaylor @enarhi @alelom @peterjamesnugent

Structure_oM: Rename Queries to Requests

---

Architecture_oM/Elements/Floor.cs
Architecture_oM/Elements/Wall.cs
Geometry_oM/Geometry_oM.csproj
Geometry_oM/Misc/SurfaceTrim.cs
Geometry_oM/Surface/NurbsSurface.cs

Closes #425
Test files are located on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%2FGeometry%5FoM%2DIssue425%2DCreationOfTrimmedNurbsSurfaceDefinition). To run it, please switch to the branches related to the following PRs:
- [#603 ](https://github.com/BHoM/BHoM/pull/603)
- [#1319](https://github.com/BHoM/BHoM_Engine/pull/1319)
- [#122](https://github.com/BHoM/Rhinoceros_Toolkit/pull/122)
- [#435](https://github.com/BHoM/Grasshopper_Toolkit/pull/435)
- [#435](https://github.com/BHoM/Revit_Toolkit/pull/435)
- [#183](https://github.com/BHoM/Dynamo_Toolkit/pull/183)
The error in Rhino -> BHoM -> Rhino convert error in …

Geometry_oM: Extension of definition of NurbsSurface to handle trims

---

Structure_oM/Results/Mesh/MeshElementResult.cs
Structure_oM/Results/Mesh/MeshResult.cs

Closes #618 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Issue-227-UpdateResultRequests?csf=1&e=S9Vtsn
Note, testfile requires https://github.com/BHoM/ETABS_Toolkit/tree/Etabs_Toolkit-%23227-UpdateResultExtractionToWorkWithNewRequest to work properly
- Bug fixed for meshFaceId being assigned incorrectly
- Removing setters from all parameters in MeshElementResults, making it fully immutable

Structure_oM: MeshFaceId correctly assigned in constructor for MeshElementResults

---

Structure_oM/Results/Mesh/MeshResult.cs

Closes #639 
Parameter in constructor in MeshResult did not match property name
Test that mesh result still can be pulled from Robot and/or Etabs:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/Issue-227-UpdateResultRequests?csf=1&e=2m8egn
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Robot_Toolkit/Issues/Issue277-UpdateResultToWorkWithResultRequest?csf=1&e=RhpZLb

Structure_oM: Fixing parameter name of MeshResult constructor

---

Structure_oM/MaterialFragments/GenericIsotropicMaterial.cs
Structure_oM/MaterialFragments/GenericOrthotropicMaterial.cs
Structure_oM/MaterialFragments/IMaterialFragment.cs
Structure_oM/SectionProperties/AluminiumSection.cs
Structure_oM/SectionProperties/CableSection.cs
Structure_oM/SectionProperties/ConcreteSection.cs
Structure_oM/SectionProperties/ExplicitSection.cs
Structure_oM/SectionProperties/GenericSection.cs
Structure_oM/SectionProperties/IGeometricalSection.cs
Structure_oM/SectionProperties/ISectionProperty.cs
Structure_oM/SectionProperties/SteelSection.cs
Structure_oM/SectionProperties/TimberSection.cs
Structure_oM/Structure_oM.csproj

Closes #555 
Closes #564 
Closes #588 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Structure_oM/Issue555-AddingTimberALuminiumAbdGenericSections?csf=1&e=HMfIUS
Note, testfile requires https://github.com/BHoM/BHoM_Engine/pull/1410
- Adding TimberSection
- Adding AluminiumSection
- Adding GenericSection to be used for section types not yet explicitly supported
- Adding GenericIsotropicMaterial
- Adding GenericOrthotropicMaterial
- Adding new IGeometricalSection interface for all sections based on IProfiles
- `IMaterialFragment` now implements `IBHoMFragment`
As this is touching the materials, thought this would be a good time to resolve #588 as well, simply making the structural material fragments into `IBHoMFragments`. Still outstanding …

Structure_oM: Adding Timber, Aluminium and generic sections and materials

---

Data_oM/Collections/GraphLink.cs
Data_oM/Collections/GraphNode.cs

Adding a generic dictionary for both node and edge attributes. Much like those used in NetworkX https://networkx.github.io/documentation/stable/reference/glossary.html#term-node-attribute
https://networkx.github.io/documentation/stable/reference/glossary.html#term-edge-attribute 
Closes #633 
Just edging this forward and hoping to get back to the discussion. 
Also relates to:
https://github.com/BuroHappoldEngineering/Qualia_Toolkit/pull/5
https://github.com/BuroHappoldEngineering/Qualia_Toolkit/issues/3
Plus:
Already I'm using decision graphs for the venue performance rating work. This proposed change or similar will help massively. 
A weighting decision graph works using the existing BHoM Graph but its also nice to store scores as a graph. This allows querying the graph for the score at …

Data_oM: Add attribute dictionary to GraphNode and GraphLink

---

.github/CODEOWNERS
BHoM.sln
Programming_oM/Nodes/BlockNode.cs
Programming_oM/Nodes/ClusterNode.cs
Programming_oM/Nodes/ConstructorNode.cs
Programming_oM/Nodes/CustomObjectNode.cs
Programming_oM/Nodes/ExplodeNode.cs
Programming_oM/Nodes/GetPropertyNode.cs
Programming_oM/Nodes/INode.cs
Programming_oM/Nodes/InitialiserNode.cs
Programming_oM/Nodes/LibraryNode.cs
Programming_oM/Nodes/LoopNode.cs
Programming_oM/Nodes/MethodNode.cs
Programming_oM/Nodes/ParamNode.cs
Programming_oM/Nodes/SetPropertyNode.cs
Programming_oM/Nodes/TypeNode.cs
Programming_oM/Others/ClusterContent.cs
Programming_oM/Others/NodeGroup.cs
Programming_oM/Params/DataParam.cs
Programming_oM/Params/INodeParam.cs
Programming_oM/Params/ReceiverParam.cs
Programming_oM/Programming_oM.csproj
Programming_oM/Properties/AssemblyInfo.cs

Provides the oM for the task covered by this PR: https://github.com/BHoM/Grasshopper_Toolkit/pull/447
This effectively removes the dependency of Grasshopper with the Node2Code toolkit. It is critical to do so since some of the code in GH related to Node2Code will later be migrated to BHoM_UI.
In term of review, this is mainly a question of testing that the Grasshopper PR still works the same ways now that the Om has been migrated.
This is simply a migration of the code from https://github.com/BHoM/Node2Code_Toolkit/pull/2 with no change other than the namespace

Programming_oM: Adding Initial code 

---

Quantities_oM/Attributes/MassPerUnitArea.cs
Quantities_oM/Attributes/MassPerUnitLength.cs
Quantities_oM/Quantities_oM.csproj

Closes #705 
As titles says, adding two missing quantity attributes.

Quantities_oM: Adding mass per unit area and mass per unit length

---

Structure_oM/Results/Bar Results/BarForce.cs
Structure_oM/Results/Bar Results/BarStrain.cs
Structure_oM/Results/Bar Results/BarStress.cs

Closes #696 
Closes #707 
- Added full compliment of strain results in `BarStrain `to mirror `BarStress`
- Updated description of `BarForce `and `BarStress `to remove any mention of normal force 
By inspection.
- Added full compliment of strain results in `BarStrain `to mirror `BarStress`
- Updated description of `BarForce `and `BarStress `to remove any mention of normal force

Structure_oM: Add full compliment of strains to BarStrain and update BarResult descriptions

---

BHoM/BHoMObject.cs

Closes #733 
You can now override a base property in a child - you can control default and descriptions like this: 
``` C#
public class Human : BHoMObject
{
/***************************************************/
/**** Properties                                ****/
/***************************************************/
[Description("This is the name the human goes by. Say hello!")]
public override string Name { get; set; } = "BrundleFly";
public List<IHumanRole> Roles { get; set; } = new List<IHumanRole>();        
/***************************************************/
```
- Local override of base BHoMObject Properties is now enabled. This is useful where the parent BHoMObject properties are also essential and defining properties for the child object. Allows setting of both context specific …

Base_oM: Base BHoMObject Properties now all Virtual

---

Dimensional_oM/IElement.cs
Dimensional_oM/IElement0D.cs
Dimensional_oM/IElement1D.cs
Dimensional_oM/IElement2D.cs

Closes #712 
The compliance link: https://github.com/BHoM/documentation/wiki/IElement-required-extension-methods
Realising as I'm doing this that you (@al-fisher ) probably had a different definition for `IElement` as per your [comment here](https://github.com/BHoM/BHoM/pull/704#pullrequestreview-363323984) 
Slightly unsure on how we would like to handle that as `IElement` is currently defined as a Spatial Interface through its extension methods.
We will probably need to add another level of interface, but that will require some more coordination than this PR

Dimensional_oM: Add Description Attributes to IElement Interfaces

---

Data_oM/Data_oM.csproj
Data_oM/Enums/GraphLinkDirection.cs
Data_oM/Enums/GraphNodeNeighbours.cs

Add an enum to determine `GraphNode` neighbours required for example in `Engine.Neighbours`
Closes #787

Data_Engine: Add generic graph query methods

---

Reflection_oM/Attributes/OldVersionAttribute.cs
Reflection_oM/Attributes/PreviousVersionAttribute.cs
Reflection_oM/Reflection_oM.csproj

See https://github.com/BHoM/BHoM_UI/pull/247 for more details
Simply add a new attribute that will enable local versioning as an attribute directly applied to a method or property
You will have to try you own here if you want to test. But you probably don't need to as it is just a very simple object definition.

Reflection_oM: Adding PreviousVersion attribute for versioning support

---

Architecture_oM/Architecture_oM.csproj
Architecture_oM/Elements/Occupancy.cs

CreatedOccupancyUnderArchoM
Closes #795 
Added occupancy object under architecture oM
This component may be utilised by Environments in vent calculation methods/people gains, for structures live loads or for egress calculations, etc.
Note that we chose to use the property "AreaPerPerson" rather than people per 100m2, so there will be dataset conversion required in the future.

Architecture_oM: Created Occupancy Under Arch oM

---

Reflection_oM/Attributes/DeprecatedAttribute.cs
Reflection_oM/Attributes/ReplacedAttribute.cs

Closes #834 
The constructor parameters should be matching the property names and types. This PR fixes that.

Reflection_oM: Fix invalid IImmutable constructor parameter names

---

Diffing_oM/DiffConfig.cs

As per title. Useful in the scenario described in: https://github.com/BHoM/Speckle_Toolkit/pull/82#issuecomment-622396529
Closes #845 
Check https://github.com/BHoM/Speckle_Toolkit/pull/82

Diffing_oM: remove CustomData from the default "Ignores" of DiffConfig

---

Geometry_oM/Curve/Ellipse.cs
Geometry_oM/Curve/NurbsCurve.cs
Geometry_oM/Curve/PolyCurve.cs
Geometry_oM/Curve/Polyline.cs

Closes #790 
Think I'll leave #789 open as it also details step two, the casts with checks
related to #850 which has the wiki page
https://burohappold.sharepoint.com/:u:/s/BHoM/EQBbBPE6BYFBlhJwbJllVxIB_ADwYP4S2qo4S03W9DWiwA?e=4BpRMQ
- `ICurve` to `PolyCurve`
- `Line`, `Polyline`, `Ellipse`, `Circle` to `NurbsCurve`
- `Circle` to `Ellipse`
- `Line` to `Polyline`
There were mentions about various UI things in the issue #789 which I think was decided as not a problem. But could be worth double checking.

Geometry_oM: Explicit casts for Curves

---

Geometry_oM/Curve/Arc.cs
Geometry_oM/Curve/Circle.cs
Geometry_oM/Curve/Ellipse.cs
Geometry_oM/Curve/Line.cs
Geometry_oM/Curve/NurbsCurve.cs
Geometry_oM/Curve/Polyline.cs

Closes #789 
There's also the wiki created in #850 
Adds all the explicit casts for curves which has a failure state. 
The right hand part of the test, which is testing that nothing breaks to bad (i.e. throws an exception), does not work as the UI does that without https://github.com/BHoM/BHoM_UI/issues/255 s fix, which is handled in https://github.com/BHoM/BHoM_UI/pull/253
https://burohappold.sharepoint.com/:u:/s/BHoM/EUt5Ob8QoL9BtmZo-qw3QvABpAdElVF6QxXzRAR8BmY9lA?e=d6pNRi
- from `PolyCurve` to any `ICurve`
- from `Ellipse` to `Arc`, `Circle`
- from `Arc` to `Circle`, `Ellipse`
- from `Polyline` to `Line`
- from `NurbsCurve` to `Line`, `Polyline`
Worth mentioning that the reason it got a bit messy in casting from `PolyCurve` to something is that C# does not support user defined casting …

Geometry_oM: Add Conditional Explicit Casts Between Curve Types.

---

Data_oM/Data_oM.csproj
Data_oM/Requests/LogicalNotRequest.cs

Closes #889
See https://github.com/BHoM/Revit_Toolkit/pull/731
- `LogicalNotRequest` has been implemented
- `Requests` property has been removed from `ILogicalRequest`
- I am not entirely happy about the name of the `Request` property (@IsakNaslundBh neither) - @al-fisher @rwemay do you have any native-speaker suggestions on that one?
- removal of property from an interface should not introduce any versioning issues, as long as the code complies everywhere, right @adecler?

Data_oM: LogicalNotRequest implemented

---

Environment_oM/Elements/Enums/PanelType.cs

Closes #898 
Added Air as a PanelType in the PanelType Enum

Add Air as PanelType

---

LifeCycleAssessment_oM/ScopeObjects/EnclosuresScope.cs
LifeCycleAssessment_oM/ScopeObjects/FoundationsScope.cs
LifeCycleAssessment_oM/ScopeObjects/LifeCycleAssessmentScope.cs
LifeCycleAssessment_oM/ScopeObjects/MEPScope.cs
LifeCycleAssessment_oM/ScopeObjects/StructuresScope.cs
LifeCycleAssessment_oM/ScopeObjects/TenantImprovementScope.cs

Closes #915 (Already closed, follow up fix)
LCA Scopeobjects take a list of IBHoMObjects instead of IElementM's in order to allow for EPD calculation on non-IElementM objects.

LifeCycleAssessment_oM: Fixed Scope Objects 

---

Environment_oM/Elements/BoundaryZone.cs
Environment_oM/Elements/Mesh.cs
Environment_oM/Environment_oM.csproj
Geometry_oM/Geometry_oM.csproj
Geometry_oM/Mesh/CellRelation.cs
Geometry_oM/Mesh/Mesh3D.cs

Closes #419 
Adds a Mesh3D object in Geometry_oM which contains all the geometrical information to rebuild the data in the issue, and a Environment object which can contain the analytical information.
Opted to mirror the cell handling by OpenFOAM, as defining cells as we define faces was a more annoying conversion (and heavy) which would be were bad if most of the methods will make use of external software's.
Will open some necessary follow up PRs in Engine and Rhino
https://github.com/BHoM/BHoM_Engine/pull/1884
https://github.com/BHoM/Rhinoceros_Toolkit/pull/167
Creates the mesh in the issue as a BHoM object
https://burohappold.sharepoint.com/:u:/s/BHoM/ESMAIxGTC_xKiBC65mlFRXcBzjwEe523U98Z6Yjn4mVLdQ?e=AtAxPw

Geometry_oM: Add Mesh3D, and Environment Mesh

---

Diffing_oM/Diff.cs
Diffing_oM/DiffConfig.cs

Closes #836
See https://github.com/BHoM/BHoM_Engine/pull/1900
- Adds the option to regulate MaxDifferences as in https://github.com/BHoM/BHoM_Engine/pull/1900
- Adds the option to regulate the PropertiesToInclude as in https://github.com/BHoM/BHoM_Engine/pull/1900

Diffing_oM: add "PropertiesToInclude" and max no of DifferentProperties in DiffConfig

---

Structure_oM/Loads/AreaTemperatureLoad.cs
Structure_oM/Loads/AreaUniformlyDistributedLoad.cs
Structure_oM/Loads/BarPointLoad.cs
Structure_oM/Loads/BarPrestressLoad.cs
Structure_oM/Loads/BarTemperatureLoad.cs
Structure_oM/Loads/BarUniformlyDistributedLoad.cs
Structure_oM/Loads/BarVaryingDistributedLoad.cs
Structure_oM/Loads/GravityLoad.cs
Structure_oM/Loads/IElementLoad.cs
Structure_oM/Loads/PointAcceleration.cs
Structure_oM/Loads/PointDisplacement.cs
Structure_oM/Loads/PointLoad.cs
Structure_oM/Loads/PointVelocity.cs
Structure_oM/Structure_oM.csproj
Structure_oM/Versioning_33.json

Closes #946 
Changing the abstract class `Load<T>` into an interface.
Renaming to `IElementLoad<T>` to better highlight intent
As no longer an abstract class but an interface, all properties have been added to all implementing classes and an direct inheritance to BHoMObejct added.
Test file testing that the Type component upgrades correctly and that all existing load classes still de-serialise correctly. Please note, for the Type component to upgrade properly, the Versioning_Toolkit needs to be built after this PR.
https://burohappold.sharepoint.com/:f:/s/BHoM/EgYptE6GOE9Hs_xqcghkGWwB7EHdw6KHumPfR6ufZJcleQ?e=B1Lfsv

Structure_oM: Turn Load<T> into IELementLoad<T>

---

MEP_oM/SectionProperties/DuctSectionProperty.cs

Closes #977
Fix argument names of constructor so they match the property names exactly. Important for serialisation to function.
General serialisation test:
https://burohappold.sharepoint.com/:f:/s/BHoM/EobV-zo3k9NCrXrp9WsnwF4BIfg0V4Xx520ZcZL94n2eEQ?e=26tEW2

MEP_oM: Fix constructor arguments for DuctSectionProperty

---

Acoustic_oM/Elements/Panel.cs

Closes #995 
As uncovered in issue in UI https://github.com/BHoM/BHoM_UI/issues/307
Static property on objects causes CreateObject initialisation issues.
To test - try the above - and it should work as expected.

Acoustic_oM: Set Acoustic.Panel PanelID Property as virtual

---

LifeCycleAssessment_oM/MaterialFragment/EnvironmentalProductDeclaration.cs
LifeCycleAssessment_oM/MaterialFragment/IEnvironmentalProductDeclarationData.cs
LifeCycleAssessment_oM/MaterialFragment/SectorEnvironmentalProductDeclaration.cs

Closes #1003 
Closes #941 
Closes #1007 
Closes #793 
Closes #791 
Additional object properties for more robust data where applicable. 
Default density value set to 0 instead of double.NaN for increased engine method reliability.
[Test File ](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/LifeCycleAssessment_Toolkit/LifeCycleAssessment_oM-%231003-EPD-Property-Updates.gh?csf=1&web=1&e=sGb5AT)

LifeCycleAssessment_oM: Update EPD Object Properties

---

Reflection_oM/Attributes/DefaultValueWarningAttribute.cs
Reflection_oM/Attributes/DoNotAutoCreateAttribute.cs
Reflection_oM/Attributes/NoAutoConstructorAttribute.cs
Reflection_oM/Attributes/RequiredAttribute.cs
Reflection_oM/Reflection_oM.csproj

Closes #731
Closes #883 
Also helps with https://github.com/BHoM/BHoM_UI/issues/205
This provides the 3 attributes we agreed on when talking about improving the control of the auto-constructor components. 
- Required properties
- Classes that should not have an auto-constructor (because they have a Create method in the engine and the two cannot coexist).
- Warning on the component when the default value of a property is used (spoiler alter, I actually intend to make it a not and not a warning to help OCD people like me that cannot stand for a component to stay orange).
Not much to test for now. It is more a matter of agreeing with the definition I created here.
I am aware that there is plan to migrate the attributes from the reflection engine to the base engine (see …

Reflection_oM: Adding attributes to better control auto-create components

---

Geometry_oM/ShapeProfiles/TaperedProfile.cs

Closes #990 
@IsakNaslundBh @JosefTaylor I have changed the input for the positions to `List<double>` as `List<decimal>` was giving me some errors about a cast from `System.Object` to `System.Double` in the BHoM UI.

Geometry_oM: Added InterpolationOrder and added shape to constructor for TaperedProfile

---

Geometry_oM/Solid/BoundaryRepresentation.cs

https://github.com/BHoM/BHoM_Engine/pull/2058 
https://github.com/BHoM/Versioning_Toolkit/pull/101
https://github.com/BHoM/Rhinoceros_Toolkit/pull/176
Closes #1016 
[Test file ](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%2FGeometry%5FoM%2DIssue1016%2DBRepVolume&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) for versioning, as well as successful conversion with volume set from Rhino
See Engine PR for modification to Translation method for BoundaryRepresentations.
Volume should be invalidated for any non-rigid body translations.
Test script shows some translations not working for some NURBS - out of scope of these PRs
But Volume should be NaN where not Null for any …

Geometry_oM: Addition of Volume as a Get only Property to BoundaryRepresentation

---

MEP_oM/ConnectionProperties/CableTrayConnectionProperty.cs
MEP_oM/ConnectionProperties/IConnectionProperty.cs
MEP_oM/Elements/CableTray.cs
MEP_oM/MEP_oM.csproj
MEP_oM/MaterialFragments/CableTrayMaterial.cs
MEP_oM/SectionProperties/CableTraySectionProperty.cs

Closes #997 
Added the definition for Cable Tray and its `SectionProperty` equivalent.
Test file [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/MEP_oM/Issue997-Add%20Cable%20Tray%20definition?csf=1&web=1&e=p8R7e7). No instructions needed.
Added new object `BH.oM.MEP.Elements.CableTray` and `BH.oM.MEP.SectionProperties.CableTraySectionProperty`.
Within `CableTraySectionProperty` the property `MEPMaterial` has been kept, but no support to it has been added in `IMEPMaterial`, as material is mostly irrelevant (I think) to cable trays holding cables.

MEP_oM: Added Cable Tray definition

---

BHoM.sln
Facade_oM/Elements/CurtainWall.cs
Facade_oM/Elements/Enums/FrameCornerType.cs
Facade_oM/Elements/Enums/FrameEdgeType.cs
Facade_oM/Elements/Enums/OpeningType.cs
Facade_oM/Elements/Enums/PanelType.cs
Facade_oM/Elements/FrameEdge.cs
Facade_oM/Elements/Opening.cs
Facade_oM/Elements/Panel.cs
Facade_oM/Facade_oM.csproj
Facade_oM/IFacadeObject.cs
Facade_oM/IProperty.cs
Facade_oM/Properties/AssemblyInfo.cs
Facade_oM/SectionProperties/FrameEdgeProperty.cs

Closes #975 
Adding initial facade om objects. These objects include critical objects for curtain walls and openings and the frame properties required to describe them to a facades-required level of detail.

Facade_oM: Creation of Initial Facade_oM

---

Analytical_oM/Analytical_oM.csproj
Analytical_oM/Results/IMeshElementResult.cs
Analytical_oM/Results/IMeshResult.cs
Structure_oM/Results/Mesh/MeshElementResult.cs
Structure_oM/Results/Mesh/MeshResult.cs

Closes #1019 
Adding IMeshResult and IMeshElement result itnerfaces to analytical_oM
Applying the interface to the structural results.
First step in aligning result display and management for Mesh results
Pulling structural results should still work with 0 difference:
https://burohappold.sharepoint.com/:f:/s/BHoM/EquJuQS0tyRNgF7YNuL5qBwBzdLgb4se7tbFNyLAODH7pQ?e=FYCxK9

Analytical_oM: Add mesh result interface

---

Structure_oM/Elements/FEMesh.cs
Structure_oM/Elements/Panel.cs
Structure_oM/SectionProperties/ConcreteSection.cs

Closes #644
Removes non-sensical default values of an empty constant thickness property for Panel and FEMesh.
Adding in default empty list for bar reinforcement on the concrete section.

Structure_oM: Fixing default values of some properties

---

Reflection_oM/Attributes/FilePathAttribute.cs
Reflection_oM/Attributes/FolderPathAttribute.cs

Closes #1081
Not needed, cosmetic change.
- path attribute classes made non-abstract

Reflection_oM: Path attribute classes made non-abstract

---

BHoM.sln
Security_oM/Elements/CameraDevice.cs
Security_oM/Enums/CameraType.cs
Security_oM/Enums/MountingType.cs
Security_oM/Properties/AssemblyInfo.cs
Security_oM/Security_oM.csproj

Closes #1078 
Created Security_oM and added the definition for CameraDevice.
Added new object `BH.oM.Security.Elements.CameraDevice`
Added new enums `BH.oM.Security.Enums.CameraType`
Added new enums `BH.oM.Security.Enums.MountingType`

Security_oM: Added Security oM with initial CameraDevice definition

---

Physical_oM/Elements/ExplicitBulk.cs
Physical_oM/Elements/SolidBulk.cs
Physical_oM/Physical_oM.csproj

Closes #1088 
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Physical_oM/Physical_oM-Issue1088-ExplicitBulk/ExplicitBulk.gh?csf=1&web=1&e=LwundV)
- Should also note that this PR changes the name of the newly created `BulkSolids` to `SolidBulk`. No versioning required since this object has likely not found its way into any workflows since its very recent creation within the 4.0 milestone. All extension methods have also been adjusted in the linked Physical_Engine PR.

Physical_oM: Create ExplicitBulk Element

---

MEP_oM/Enums/MechanicalEquipmentType.cs
MEP_oM/Equipment/MechanicalEquipment.cs
MEP_oM/MEP_oM.csproj

Closes #1094 
Generic Mechanical Equipment Object added
MechanicalEquipmentType enum added
Workflow Prototype (assign type enum after pull):
@Hmullerjones to review the enum for the mechanical equipment types for UK understanding of my American verbiage :)

MEP_oM: Addition of Generic Mechanical Equipment object

---

Facade_oM/Facade_oM.csproj
Facade_oM/Fragments/ConstructionOffset.cs
Facade_oM/Fragments/ConstructionOffsetFragment.cs

Closes #1140 
Adding fragment to Facade_oM that defines offset distance. This can be applied to wall cross sections or glazing cross sections to offset them from the facade centerline.

Facade_oM: ConstructionOffsetFragment

---

Reflection_oM/Attributes/InputAttribute.cs
Reflection_oM/Attributes/MultiOutputAttribute.cs
Reflection_oM/Attributes/OutputAttribute.cs

Closes #1160
After the change on the Quantity property of those attributes, the classes became non compliant (missing matching constructor) and therefore failed to deserialise correctly.
Note that, to deserialise correctly, we also need a correction of the property name in the versionning `Upgrade.json` file. Will push soon with a series of other fixes on versioning once the current PR is merged

Reflection_oM: Fix non compliant IImmutable attributes

---

Lighting_oM/Results/Illuminance/Lux.cs

Closes #1170
As per issue. Pretty straightforward correction of a constructor that was marked as `protected`

Lighting_oM: Make constructor public instead of protected

---

Programming_oM/Nodes/BlockNode.cs
Programming_oM/Nodes/LoopNode.cs
Programming_oM/Params/DataParam.cs
Programming_oM/Params/INodeParam.cs
Programming_oM/Params/ReceiverParam.cs

https://github.com/BHoM/BHoM_Engine/pull/2286
https://github.com/BHoM/CSharp_Toolkit/pull/41
https://github.com/BHoM/Grasshopper_Toolkit/pull/592
https://github.com/BHoM/Versioning_Toolkit/pull/135
Closes #1172 
See issue. Pretty straightforward removal of a property. The key thing to test is that the Node2Code component is still working correctly as this is the only place where `ParentId` was actually used.
@rolyhudson , this should probably make the most sense to you as this is very similar to what we did on the GraphFlow stuff.
@FraserGreenroyd , @IsakNaslundBh , adding you more as a FYI as the whole concept of Immutability is close to you. This was an interesting case as there wasn't really a good combination of  constructor and get only properties that would prevent all possible …

Programming_oM: Remove ParentId property from INodeParam

---

Test_oM/Results/EventMessage.cs
Test_oM/Test_oM.csproj

Closes #1181 
Adds `EventMessage` class meant to be a place to store information from a Debug.Event as `Information` on the `TestResult`.

Test_oM: Adding EventMessage

---

Graphics_oM/Graphics_oM.csproj
Graphics_oM/Render/IRender.cs
Graphics_oM/Render/RenderGeometry.cs
Graphics_oM/Render/RenderText.cs

To view these objects in Rhino / Grasshopper
https://github.com/BHoM/Rhinoceros_Toolkit/pull/202
https://github.com/BHoM/Grasshopper_Toolkit/pull/602
Adds `RenderGeometry` and `RenderText` objects.
Closes #1190
[Examples of usage](https://github.com/BHoM/BHoM_Engine/pull/2288#issuecomment-776147787)
Set of tests [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Graphics_oM/%231191_Add_basic_graphical_objects?csf=1&web=1&e=f9Vp5s)
Run through in numbered order.
Noting that currently default bake behaviour for Render objects ALWAYS results in baking geometry or text with specified colour.
Destination layer is set by user either as current layer when baking via ctrl+space+bake
or set in attributes dialog when baking via right click …

Graphics_oM: Add basic graphical objects

---

Humans_oM/Humans_oM.csproj
Humans_oM/Versioning_41.json

Property name change versioned for CValueSettings
Previous version attribute for the CValueAnalysis method
Closes #1221 
Closes #https://github.com/BHoM/BHoM_Engine/issues
Old components and old json strings in this [file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Humans_oM/%231221-CvalueVersioning/%231221_cvalueversioning.gh?csf=1&web=1&e=D0d4O0)

Humans_oM: Add versioning for changes to CvalueAnalysis

---

BHoM.sln
Versioning_oM/Properties/AssemblyInfo.cs
Versioning_oM/VersioningEvent.cs
Versioning_oM/Versioning_42.json
Versioning_oM/Versioning_oM.csproj

https://github.com/BHoM/Versioning_Toolkit/pull/159
This PR is done within the context of solving this issue: https://github.com/BHoM/BHoM_UI/issues/389
The reason for adding this project is to store the new VersioningEvent class that will be used to collect the list of all upgrades that occurred on BHoM objects and components.
This can be tested within the context of the related PR in the BHoM Engine repo or with the related PR in the BHoM_UI.

Versioning_oM: Add oM from Versioning_Toolkit with VersioningEvent

---

MEP_oM/Enums/FittingType.cs
MEP_oM/MEP_oM.csproj
MEP_oM/System/CableTray.cs
MEP_oM/System/Fittings/Fitting.cs
MEP_oM/Versioning_43.json

Closes #1034 
Adds a generic fitting object with basic properties and removes connection properties.
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%2FMEP%5FoM%2F%231034%2DAddGenericFittingObject)
Added `BH.oM.MEP.System.Fittings.Fitting`
Added `BH.oM.MEP.Enum.FittingType`
Modified `BH.oM.MEP.System.CableTray`
Removed `BH.oM.MEP.System.ConnectionProperties.IConnectionProperty`
Removed `BH.oM.MEP.System.ConnectionProperties.CableTrayConnectionProperty`

MEP_oM: Add new fitting object

---

Architecture_oM/BuildersWork/Opening.cs

Closes #1257
See https://github.com/BHoM/BHoM_Engine/pull/2572
I was considering between different numbers of dimensions to be applied, but finally I came to a conclusion that the closest concept is 0D since the location of the opening is represented by `Cartesian`, ergo its position in space is a point. Happy to hear others' opinion! @rolyhudson @al-fisher @tiagogrossi @kayleighhoude @michaelhoehn

Architecture_oM: IElement0D implemented by BuildersWork.Opening

---

BHoM/BHoMObject.cs
BHoM/Interface/IBHoMObject.cs

Closes #1264
Following https://github.com/BHoM/admin/issues/9#issuecomment-886638611, all references to the method `GetShallowClone` of BHoMObject have been removed in favour of Engine methods `DeepClone` and `ShallowClone` that do not require implementation.
This has to be merged in parallel with the PR that targets https://github.com/BHoM/XML_Toolkit/issues/532 so that also the last remaining implementation of a BHoMObject's GetShallowClone is removed.
As part of https://github.com/BHoM/admin/issues/9#issuecomment-886638611, all references to the method have been removed. Only test needed is for everything to compile successfully.

BHoM: Removed GetShallowClone method from IBHoMObject and BHoMObject

---

BHoM/Interface/IPersistentAdapterId.cs

BHoM: IPersistentAdapterId not to require set on PersistentId

---

Analytical_oM/Analytical_oM.csproj
Analytical_oM/Results/IAnalysisResult.cs
Analytical_oM/Results/ICasedResult.cs
Analytical_oM/Results/IMeshElementResult.cs
Analytical_oM/Results/IMeshResult.cs
Analytical_oM/Results/IObjectIdResult.cs
Analytical_oM/Results/IResult.cs
Analytical_oM/Results/IResultCase.cs
Analytical_oM/Results/ITimeStepResult.cs
Analytical_oM/Results/ShortestPathResult.cs
Environment_oM/Results/Mesh/MeshElementResult.cs
Environment_oM/Results/Mesh/MeshResult.cs
LifeCycleAssessment_oM/Results/LifeCycleAssessmentElementResult.cs
LifeCycleAssessment_oM/Results/LifeCycleAssessmentResult.cs
LifeCycleAssessment_oM/Results/ProjectLifeCycleAssessmentResult.cs
Lighting_oM/Results/Mesh/MeshElementResult.cs
Lighting_oM/Results/Mesh/MeshResult.cs
Structure_oM/Results/Bar Results/IBarDisplacement.cs
Structure_oM/Results/IStructuralResult.cs
Structure_oM/Results/Mesh/IMeshDisplacement.cs
Structure_oM/Results/Mesh/MeshResult.cs
Structure_oM/Results/Nodal Results/INodeDisplacement.cs
Test_oM/Results/InputOutputComparisonDiffing.cs
Test_oM/Results/InputOutputComparisonSummary.cs
Test_oM/Results/InputOutputDifference.cs

Closes #1278
Closes #1278
The base IResult interface is now empty (does not require any specific property). In its stead, you can find:
- `IObjectIdResult`, that asks for an `ObjectId`
- `ICasedResult`, that asks for a `ResultCase`
- `ITimeStepResult`, that asks for a `TimeStep`
In addition, to maintain compatibility with all existing functionality, I added a `IAnalyticalResult` that implements all the three interfaces above, so it effectively replicates what `IResult` used to be. I modified all existing implementations of `IResult` to reference to `IAnalyticalResult` instead, so functionality wise we should look exactly the same as before.
The advantage of this approach is that you are no longer forced to implement all properties that `IResult` used to force you to implement, if they do …

Analytical_oM: Reformulate the IResult interface

---

BHoM/Enumeration.cs
BHoM/Interface/IEnum.cs

Closes #1293
See issue. Current implementation in the context of the Embodied Carbon toolkit
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Base_oM/%231294%20-%20Enumeration?csf=1&web=1&e=eX3XoG
You will need the following PRs to do the testing:
- https://github.com/BHoM/BHoM_Engine/pull/2637
- https://github.com/BHoM/Excel_Toolkit/pull/310
- https://github.com/BuroHappoldEngineering/EmbodiedCarbon_Toolkit/pull/1
There's a lot that can be done to make the Enumerations more user friendly in the UI (e.g. make it behave exactly like a regular enum in the UI) but this PR is just about laying the foundation for this new type of object. It has been working great for me in the context of the Carbon calculator tool for all stages of workflow …

Base_oM: Adding Enumeration object

---

BHoM/BaseComparisonConfig.cs
BHoM/ComparisonInclusion.cs
BHoM/NamedNumericTolerance.cs
BHoM/NamedSignificantFigures.cs
BHoM/Versioning_50.json
Diffing_oM/Delta.cs
Diffing_oM/Diff.cs
Diffing_oM/DiffingConfig.cs
Diffing_oM/ObjectDifferences.cs
Diffing_oM/PropertyDifference.cs
Diffing_oM/Versioning_50.json

Closes https://github.com/BHoM/BHoM/issues/1308
Closes #1318 
**Note**: this replaces https://github.com/BHoM/BHoM/pull/1306 due to rebase conflicts.
The new Diff object has a simplified structure for the `ModifiedPropertiesPerObject` property (no more `Dictionary<Dictionary<Tuple<object, object>>>`). 
Added a `ComparisonInclusion` object that stores the result of the method of the same name, which can be implemented in specific Toolkits. This latter is called automatically by Diffing/Hash methods to determine if/how to include certain property differences. See https://github.com/BHoM/BHoM_Engine/pull/2699.
Created a `ComparisonConfig` abstract class to allow Toolkits to implement more specific configurations. A default ComparisonConfig implementation is provided too.
This also removes …

Diffing_oM: reworked `Diff` class; added `ComparisonInclusion` and a `ComparisonConfig` base class

---

BHoM/BaseComparisonConfig.cs
BHoM/Versioning_50.json

Closes #1331
Closes #1332
See the changelog for details.
Make sure you recompile Versioning after compiling this branch.
Open the following script, that was created before this change:
https://burohappold.sharepoint.com/:f:/s/BHoM/EjfEz1RSi3pEpKpJacZnlMQBXBHsA5f5C8c-eht02C2FlQ?e=wL4dzw
all the wires should be connected and versioning should have renamed the property called `CustomDataKeysToInclude` to `CustomDataKeysToConsider`.
Functionality itself is not affected, so testing is not needed, but it can be tested with:
https://burohappold.sharepoint.com/:f:/s/BHoM/ElkWAuBU0CpNhyNhwF96LlEBqkxJgHX3AhBOGlnA4bBwag?e=Kr2FMc
- Renamed `CustomDataKeysToInclude` to `CustomDataKeysToConsider`
- Changed the ordering of the properties in `ComparisonConfig` for ease of use
- Corrected/improved some …

Base_oM: `ComparisonConfig` properties description, naming and order revised for compliance

---

Facade_oM/Fragments/BoundingBox.cs
Facade_oM/Fragments/FrameExtensionBox.cs
Facade_oM/Fragments/GlazingLocation.cs

Closes #1233 
Adds 2 new fragments -
1. FrameExtensionBox is a curve that encloses the portion of a mullion cross section to be extruded for mullion depth methods.
2. GlazingLocation is a double that gives the distance between the cross section origin and the edge of glazing 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Facade_oM/%231233-ExtrusionBoundingBox?csf=1&web=1&e=bRL6iB

Facade_oM: Extrusion Bounding Box Fragment

---

Analytical_oM/Results/IMeshResult.cs
Analytical_oM/Results/IResultCollection.cs
Environment_oM/Results/Mesh/MeshResult.cs
LifeCycleAssessment_oM/Results/LifeCycleAssessmentResult.cs
Lighting_oM/Results/Mesh/MeshResult.cs
Structure_oM/Results/Mesh/MeshResult.cs
Test_oM/Results/InputOutputComparison.cs

Closes #1359 
Changing property type from `ReadOnlyCollection` to `IReadOnlyList` which allows for the use of the covariant `out` keyword on the interface. This means that an engine method written to accept for example an `IResultCollection<IResult>` should accept an `IResultCollection<BarForce>` similar to the way `IEnumerable<object>` etc works.
Also will give similar benefits to the `IMeshResult<T>` interface which also will be able to use the out keyword.
With this change the non-generic class can safely be removed as the only reason for this interface was to help with filtering.
Some toolkits will need slight alignment before this is merged. Raising PR for @alelom to have a first look.

Analytical_oM: IResultCollection generic update

---

Analytical_oM/Results/ResultFilter.cs

Closes #1375 
Changing to hashsets of string rather than hashsets of IComparable for result filtering to allow for better usability from the UI.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Analytical_oM/%231376-ChangeResultFiltersToStringHashSets?csf=1&web=1&e=ZxWpLB

Analytical_oM: Change ResultFilter HashSets to string

---

Graphics_oM/Render/RenderGeometry.cs
Graphics_oM/Render/Texture.cs

Closes #485
Add graphics texture class to handle rendering of surface and meshes. Defaults to BHoM Pink with no bitmap.
Adding a explicit casting from Colour to Texture to allow easier generation from the UI.
General intended logic of the class is that the Colour property always gives the colour of the edges, while the Texture property gives the colour or texture of the mesh/surface faces. If the texture is not set, the display should fall back on using the colour property instead.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Graphics_oM/%231389-AddGraphsicsRenderTexture?csf=1&web=1&e=NxVT3M
- Can also add transparency and bumb maps if we like, but kept it simple, only adding main texture in the first push.
- Later PR to handle …

Graphics_oM: Add graphics render texture

---

Facade_oM/Fragments/UValueContinuous.cs

Closes #1421 
Adds new fragment UValueContinuous which represents the u-value of continuous insulation and/or layers that are not impacted by thermal bridging from the frameedgeproperties.

Facade_oM: Add UValueContinuous Fragment

---

Structure_oM/MaterialFragments/Timber.cs
Structure_oM/Versioning_60.json

Closes #1409 
Closes #1411 
Added rolling shear property
Changed name of rolling shear from F_v to F_r
Added distinction between characteristic and mean values for all modulus properties. I appreciate this may have been omitted for clarity with US users maybe? @JosefTaylor please have a look and see if my descriptions are suitable for both sides of the pond thanks.

Structure_oM: Adding missing rolling shear modulus and distinction between characteristic and average values for all moduli properties

---

Physical_oM/Materials/MaterialTakeoff.cs
Physical_oM/Materials/VolumetricMaterialTakeoff.cs

Closes #1422 
Adds class for MaterialTakeoff. Class for storing a set of materials and the corresponding volumes of said materials.

Physical_oM: Add MaterialTakeoff class

---

Physical_oM/Elements/MeshElement.cs

Closes #1451
Adding a simple `MeshElement` class. First use case to be able to make a simplified representation of BIM objects, where parameters are to be stored in software specific fragments, and the Mesh property is to host the mesh representation of the object.
To be tested in anger in various workflows in other toolkits. For this first push just good to get the object in for which code review should suffice.

Physical_oM: Add MeshElement

---

Facade_oM/Fragments/UValueCavity.cs

Closes #1424 
Adds new fragment UValueCavity which represents the u-value of cavity insulation which is not continuous across frameedges.

Facade_oM: Add UValueCavity Fragment

---

LifeCycleAssessment_oM/Results/ElementResult.cs
LifeCycleAssessment_oM/Results/MaterialResult.cs

Closes #1448
Adding new LCA result classes:
- ElementResult - can replace the current result class if this PR is accepted. Stores information about how to identify the result as well as total quantity and a breakdown of quantity evaluated per material.
- MaterialResult - New result class, storing information about quantity per material. Can be per element as part of ElementResult or total for a particular material.
Adding as new classes as a first step. If agreed we could replace the current ResultClasses in the oM.

LifeCycleAssesment_oM: Add new LCA result classes

---

Structure_oM/SurfaceProperties/BiDirectionalVoided.cs
Structure_oM/SurfaceProperties/HollowCore.cs
Structure_oM/SurfaceProperties/HollowCoreOpeningProfiles/CircularHollowCoreOpeningProfiles.cs
Structure_oM/SurfaceProperties/HollowCoreOpeningProfiles/ElongatedCircularHollowCoreOpeningProfiles.cs
Structure_oM/SurfaceProperties/HollowCoreOpeningProfiles/IHollowCoreProfile.cs
Structure_oM/SurfaceProperties/OneDirectionalVoided.cs
Structure_oM/SurfaceProperties/ToppedSlab.cs

Closes #1480 
Closes #1481 
Adds a series of new SurfacePropery classes.
- Voided: One and two directional
- Hollow core (with a first two common opening profile types)
- Topped slab, to enable for example a precast slab with concrete topping.
https://burohappold.sharepoint.com/:f:/s/BHoM/EnlCAJUsxb5Ckyaz48Avm1gBomY2EBiRpl1Fy8Vemwwozg?e=YoFIFQ

Structure_oM: Add new surface properties

---

BHoM/BHoM.csproj

Fixes #1489 
Steps to test:
- Delete your `C:\ProgramData\BHoM\Settings` folder (or rename it) and try to open BHoM in Grasshopper
- You should get invocation errors, and the BHoM ribbon is devoid of any useful content
- Compile this PR
- You should get an empty `Settings` folder in `C:\ProgramData\BHoM`
- Open Grasshopper
- You should get 0 errors, and the BHoM ribbon should have its usual content

BHoM: Have compiling BHoM make a Settings directory.

---

Lighting_oM/Elements/Luminaire.cs

Closes #1500 
As per the title, the Property previously named Direction has been changed to a Property named Orientation with type Basis.

Lighting_oM: Changed Luminaire Orientation Property name and Type to Basis to Align with similar Elements

---

LifeCycleAssessment_oM/Versioning_62.json

Closes #1512
As stated in issue:
The LifeCycleAssessmentScope was changed from a BHoMObject to not a BHoMObject a few versions ago.
With the new improved [Serialiser_Engine](https://github.com/BHoM/BHoM_Engine/pull/3042) this is flagged up as an issue requiring versioning, which is correct as the data for the base properties has nowhere to be put.
Message for deleted is to be added for all of those properties.
This is not really relating to versioning happening in 6.2, but think it is still fine to add here as it is the serialisation fixes that helps this getting flagged.
This will not trigger on main/dev branches, but still think it is fine to merge in before Serialiser_Engine as it wont hurt anything.

LifeCycleAssesment_oM: Add message for deleted for implicitly removed properties

---

Physical_oM/Materials/GeneralMaterialTakeoff.cs
Physical_oM/Materials/TakeoffItem.cs

Closes #1502 
Adds a general takeoff object able to store a multitude of quantities associated with a particular material
Done in support of https://github.com/BHoM/LifeCycleAssessment_Toolkit/pull/314 to help further simply evaluation process and remove last bits of takeoff responsibility from the LCA_Engine.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Physical_oM/%231516-AddGeneralTakeoffObject?csf=1&web=1&e=iAsS7e

Phsyical_oM: Adds a general Material Takeoff object

---

Diffing_oM/Diff.cs

Closes #1546
Standard test procedure for diffing.

Diffing_oM: null coalescence of optional Diff constructor parameters added

---

Facade_oM/Elements/Enums/OpeningType.cs

Related to https://github.com/BHoM/BHoM_Engine/issues/3145
- Added new enum OpeningTypes required to run new spandrel calculation methods on BHoM_Engine.
- Deleted obsolete OpeningType enums.
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Facade_Engine/BHoM%20PR%20Test%20Files/230906_SpandrelAWTestFile.gh?csf=1&web=1&e=1rxpMK)

Facade_oM: Updated OpeningType enums

---

README.md
docs/CODE_OF_CONDUCT_FOR_BOTS.md
docs/GOVERNANCE.md

Fixes #1562
I've done through all our `docs` and `.md` files and updated all references to `master` to be `main`, and updated all links from the GitHub wiki to the `bhom.xyz/documentation` pages instead.
I also updated some of the names in the Governance document while I was there to reflect the current state of affairs 😄

BHoM: Update documentation links and references

---

Dimensional_oM/IElement0D.cs
Dimensional_oM/IElement1D.cs
Dimensional_oM/IElement2D.cs
Dimensional_oM/IElementM.cs

Fixing the Documentation URLs to the IElement Required Methods
As part of the Documentation restructuring as per issue https://github.com/BHoM/documentation/issues/85
See also https://github.com/BHoM/BHoM_Engine/pull/3216#issue-2008248203 for similar and further context

Dimensional_oM: Updating DocumentationURL ref IElement Required Methods

---

Structure_oM/Loads/GeometricalLineLoad.cs

A GeometricalLineLoad currently does not have an attribute that represents the object(s) on which it is placed or which should be influenced by it. This PR should add an aditional attribute representing Panels which the GeometricalLineLoad is potentially influencing. 
Closes #1564 
- [Test File](https://burohappold.sharepoint.com/:u:/s/BHoM/EXjZFLEOqjxLhvPfr06fLusBIcaQr2MyubvPd3PGA3sdkw?e=Li8dN1)
- Updated `GeometricalLineLoad` to implement the `IElementLoad<IAreaElement>`;
- Added the 'Objects' attribute to `GeometricalLineLoads`, this will enable the load to be applied to specific `Panel` elements (which is required in some use cases).

Structure_oM: Added IAreaElements to GeometricalLineloads

---

Analytical_oM/Elements/ILink.cs
Analytical_oM/Versioning_71.json
Structure_oM/Elements/Bar.cs
Structure_oM/Versioning_71.json

Fixes #487 
- Analytical_oM `ILink` property updated from `StartNode` to `Start` and from `EndNode` to `End`
- Structure_oM `Bar` object updated accordingly based on Analytical oM interface update

Analytical_oM: Rename StartNode/EndNode to Start/Node

---

Analytical_oM/Graph/Graph.cs
Analytical_oM/Graph/IRelation.cs
Analytical_oM/Graph/Projection/GeometricProjection.cs
Analytical_oM/Graph/Projection/GraphicalProjection.cs
Analytical_oM/Graph/Projection/IProjection.cs
Analytical_oM/Graph/Projection/SpatialProjection.cs
Analytical_oM/Graph/Relation.cs
Analytical_oM/Graph/RelationDirection.cs
Analytical_oM/Results/ShortestPathResult.cs
Analytical_oM/Versioning_71.json

Analytical_oM: Elevate Graph objects from Elements sub folder to own primary folder

---

BHoM/BaseComparisonConfig.cs
BHoM/ComparisonConfig.cs

Closes #1587 
See https://github.com/BHoM/BHoM_Engine/pull/3268

Base_oM: add a `UseGeometryHash` option to the `BaseComparisonConfig`

---

BHoM/Interface/IInitialisationSettings.cs
BHoM/UsageLogEntry.cs
BHoM/Versioning_71.json

Fixes https://github.com/BHoM/BHoMAnalytics_Toolkit/issues/73
Promotes up `IInitialisationSettings` interface from UI_oM to Base_oM. This then removes the need for BHoMAnalytics_Toolkit to depend on BHoM_UI, which in turn removes the need for BHoM_UI to be a nuget and removes the warning/error raised from the zero code tools @adecler is working on when using BHoMAnalytics_Toolkit nuget but the `NetFramework` version of BHoM_UI is incompatible.

BHoM: Promote IInitialisationSettings interface from UI_oM

---

Structure_oM/MaterialFragments/Timber.cs

Closes #1518 
[Test script](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM/Structure_oM/%231518-UpdateTimberToITimber.gh?csf=1&web=1&e=oFcHfa)
- Updated `Timber` material to inherit the `ITimber` interface;
This will fix the issue of using the following datasets Structure\Materials\MaterialsEurope\SawnTimber
Structure\Materials\MaterialsEurope\Glulam with the `Create` methods for a `TimberSection`.

Structure_oM: Update Timber Material to be inherit ITimber

---

Search_oM/SearchResult.cs

Closes #1627 
[#3376-SearchEngineUTFailure](https://burohappold.sharepoint.com/:u:/s/BHoM/EQzznzpXDXBJo2pN_2sQB64BEjTLBiLoysn7RLHbf_wDGw?e=oTCArY)
- Updated constructor for `MatchScore` from `int` to `double` to reflect the changes made for the property;

Search_oM: Update constructor for MatchScore

---

Quantities_oM/Attributes/ElectricConductivity.cs

Closes #1662 
- Add quantity for `ElectricConductivity`
I have used `Electric` prefix to match `Current` and the convention used on UnitsNet.

Quantities_oM: Add ElectricConductivity
